import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {lessons,fvLesson,cfoLesson,fwftLesson,aeoLesson,fabLesson,fwfhLesson,fcLesson,csLesson,msLesson,anLesson,vhLesson,emLesson,lessonsBase,toddlerBase} from '../src/lessons.mjs';
const read=f=>readFileSync(f,'utf8');
const l2=read('dist/newborn/6-12-weeks/faces-and-visual-tracking/index.html');
const l3=read('dist/baby/3-4-months/colors-and-first-objects/index.html');
const l4=read('dist/baby/4-6-months/first-words-familiar-things/index.html');
const l5=read('dist/baby/6-9-months/animals-everyday-objects/index.html');
const l6=read('dist/baby/9-12-months/first-actions-body-parts/index.html');
const l7=read('dist/toddler/12-18-months/first-words-food-home/index.html');
const l8=read('dist/toddler/18-24-months/first-concepts-big-small-up-down/index.html');
const l9=read('dist/toddler/2-years/colors-and-shapes/index.html');
const l10=read('dist/toddler/2-years/matching-and-sorting/index.html');
const l11=read('dist/toddler/2-years/animals-and-sounds/index.html');
const l12=read('dist/toddler/2-years/vehicles-and-sounds/index.html');
const l13=read('dist/toddler/2-years/emotions-and-feelings/index.html');
const l13pv=read('dist/toddler/2-years/emotions-and-feelings/print/index.html');
const ct1=read('dist/toddler/2-years/circle-time/hello-school/index.html');
const cthub=read('dist/toddler/2-years/circle-time/index.html');
const mc=read('dist/my-classroom/index.html');
const checkLesson=(html,L)=>{
 assert.ok(html.includes('rel="canonical" href="https://kiddo-school.pages.dev'+L.path+'"'));
 assert.ok(html.includes('<title>'+L.seoTitle.replace(/&/g,'&amp;')+' | Kiddo.school</title>'));
 assert.ok(html.includes('content="'+L.description+'"'));
 assert.ok(html.includes('<h1>'+L.h1.replace(/&/g,'&amp;')+'</h1>'));
 assert.ok(html.includes(L.eyebrow));
 for(const [k,v] of L.chips)assert.ok(html.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok([...html.matchAll(/Start Today’s Class/g)].length>=2);
 assert.ok(html.includes('data-lesson-viewer'));
 assert.ok(html.includes('data-lv-prev>Previous</button>'));
 assert.ok(html.includes('data-lv-next>Next</button>'));
 assert.ok(html.includes('data-lv-full>Full screen</button>'));
 assert.ok(html.includes('data-lv-finish>Finish</button>'));
 assert.ok(html.includes('Card 1 of '+L.cards.length));
 assert.ok(html.includes('<figure class="lesson-cover"><img src="'+L.ogImage+'" width="'+L.cover.w+'" height="'+L.cover.h+'"'));
 assert.ok(html.includes('<h2>'+L.howTo.heading+'</h2>'));
 for(const p of L.howTo.paragraphs)assert.ok(html.includes(p),p.slice(0,40));
 assert.ok(html.includes('guides, not tests or developmental deadlines'));
 for(const [label,href] of L.pills.items)assert.ok(html.includes(`href="${href}">${label}</a>`));
 assert.ok(html.includes('BreadcrumbList'));
 assert.ok(html.includes('property="og:image" content="'+L.ogImage+'"'));
 assert.ok(html.includes('name="twitter:card" content="summary_large_image"'));
};
test('lesson 2 follows the Newborn 2 spec with cover, cards and wiring',()=>{
 checkLesson(l2,fvLesson);
 assert.ok(l2.includes('NEWBORN 2 · LESSON 2'));
 assert.ok(l2.includes('<img src="'+fvLesson.ogImage+'" width="1414" height="2000"'));
 assert.doesNotMatch(l2,/loading="lazy"[^>]*cover\.webp|cover\.webp[^>]*loading="lazy"/);
 assert.ok(l2.includes('Previous lesson'));
 assert.ok(l2.includes('href="/newborn/0-6-weeks/high-contrast-cards/"'));
 assert.ok(l2.includes('Birth–6 Weeks'));
 assert.ok(l2.includes('Next lesson'));
 assert.ok(l2.includes('href="/baby/3-4-months/colors-and-first-objects/"'));
 const files=[...l2.matchAll(new RegExp(lessonsBase.replace(/\./g,'\\.')+'faces-and-visual-tracking-6-12-weeks/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(files.length,12,'grid shows each card exactly once');
 assert.deepEqual([...new Set(files)],fvLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.match(l2,/BreadcrumbList[\s\S]*"name":"Newborn"[\s\S]*"name":"6–12 Weeks"[\s\S]*"name":"Faces & Visual Tracking"/);
});
test('lesson 3 follows the Infant 1 spec with Try Together and coming-soon next',()=>{
 checkLesson(l3,cfoLesson);
 assert.ok(l3.includes('INFANT 1 · LESSON 3'));
 assert.ok(l3.includes('TRY TOGETHER'));
 assert.ok(l3.includes('<h2>Little things to say.</h2>'));
 for(const p of cfoLesson.tryTogether)assert.ok(l3.includes('<li>'+p+'</li>'),p);
 assert.ok(l3.includes('Previous lesson'));
 assert.ok(l3.includes('href="/newborn/6-12-weeks/faces-and-visual-tracking/"'));
 assert.ok(l3.includes('6–12 Weeks'));
 assert.ok(l3.includes('Next lesson'));
 assert.ok(l3.includes('href="/baby/4-6-months/first-words-familiar-things/"'));
 assert.ok(l3.includes('4–6 Months'));
 const files=[...l3.matchAll(new RegExp(lessonsBase.replace(/\./g,'\\.')+'colors-and-first-objects-3-4-months/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(files.length,12,'grid shows each card exactly once');
 assert.deepEqual([...new Set(files)],cfoLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.match(l3,/BreadcrumbList[\s\S]*"name":"Baby"[\s\S]*"name":"3–4 Months"[\s\S]*"name":"Colors & First Objects"/);
});
test('lesson 4 follows the Infant 2 spec with Try Together and a real link to lesson 5',()=>{
 checkLesson(l4,fwftLesson);
 assert.ok(l4.includes('INFANT 2 · LESSON 4'));
 assert.ok(l4.includes('TRY TOGETHER'));
 assert.ok(l4.includes('<h2>Little things to say.</h2>'));
 for(const p of fwftLesson.tryTogether)assert.ok(l4.includes('<li>'+p+'</li>'),p);
 assert.ok(l4.includes('Previous lesson'));
 assert.ok(l4.includes('href="/baby/3-4-months/colors-and-first-objects/"'));
 assert.ok(l4.includes('3–4 Months'));
 assert.ok(l4.includes('Next lesson'));
 assert.ok(l4.includes('href="/baby/6-9-months/animals-everyday-objects/"'));
 assert.ok(l4.includes('6–9 Months'));
 const files=[...l4.matchAll(new RegExp(lessonsBase.replace(/\./g,'\\.')+'first-words-familiar-things-4-6-months/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(new Set(files).size,11,'each card present exactly once (baby-face card reserved: artwork never shipped)');
 assert.deepEqual([...new Set(files)],fwftLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.match(l4,/BreadcrumbList[\s\S]*"name":"Baby"[\s\S]*"name":"4–6 Months"[\s\S]*"name":"First Words & Familiar Things"/);
});
test('lesson 5 follows the Explorer 1 spec with Try Together, Find It in Real Life and a real link to lesson 6',()=>{
 checkLesson(l5,aeoLesson);
 assert.ok(l5.includes('EXPLORER 1 · LESSON 5'));
 assert.ok(l5.includes('TRY TOGETHER'));
 assert.ok(l5.includes('<h2>Little things to say.</h2>'));
 for(const p of aeoLesson.tryTogether)assert.ok(l5.includes('<li>'+p+'</li>'),p);
 assert.ok(l5.includes('REAL-WORLD CONNECTION'));
 assert.ok(l5.includes('<h2>Find It in Real Life</h2>'));
 assert.ok(l5.includes(aeoLesson.realWorld.copy));
 for(const p of aeoLesson.realWorld.examples)assert.ok(l5.includes('<li>'+p+'</li>'),p);
 assert.ok(l5.includes('Previous lesson'));
 assert.ok(l5.includes('href="/baby/4-6-months/first-words-familiar-things/"'));
 assert.ok(l5.includes('4–6 Months'));
 assert.ok(l5.includes('Next lesson'));
 assert.ok(l5.includes('href="/baby/9-12-months/first-actions-body-parts/"'));
 assert.ok(l5.includes('9–12 Months'));
 const files=[...l5.matchAll(new RegExp(lessonsBase.replace(/\./g,'\\.')+'animals-everyday-objects-6-9-months/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(new Set(files).size,12,'each card present exactly once (the cat card also fronts the set: the folder has no cover file)');
 assert.deepEqual([...new Set(files)],aeoLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.match(l5,/BreadcrumbList[\s\S]*"name":"Baby"[\s\S]*"name":"6–9 Months"[\s\S]*"name":"Animals & Everyday Objects"/);
});
test('lesson 6 follows the Explorer 2 spec with Try Together, Practice in Real Life and a real link to lesson 7',()=>{
 checkLesson(l6,fabLesson);
 assert.ok(l6.includes('EXPLORER 2 · LESSON 6'));
 assert.ok(l6.includes('TRY TOGETHER'));
 assert.ok(l6.includes('<h2>Little things to say.</h2>'));
 for(const p of fabLesson.tryTogether)assert.ok(l6.includes('<li>'+p+'</li>'),p);
 assert.ok(l6.includes('REAL-WORLD CONNECTION'));
 assert.ok(l6.includes('<h2>Practice in Real Life</h2>'));
 assert.ok(l6.includes(fabLesson.realWorld.copy));
 for(const p of fabLesson.realWorld.examples)assert.ok(l6.includes('<li>'+p+'</li>'),p);
 assert.ok(l6.includes('Previous lesson'));
 assert.ok(l6.includes('href="/baby/6-9-months/animals-everyday-objects/"'));
 assert.ok(l6.includes('6–9 Months'));
 assert.ok(l6.includes('Next lesson'));
 assert.ok(l6.includes('href="/toddler/12-18-months/first-words-food-home/"'));
 assert.ok(l6.includes('12–18 Months'));
 const files=[...l6.matchAll(new RegExp(lessonsBase.replace(/\./g,'\\.')+'first-actions-body-parts-9-12-months/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(files.length,12,'grid shows each card exactly once');
 assert.deepEqual([...new Set(files)],fabLesson.cards.map(c=>c.file.replace('.webp','')));
 for(const c of fabLesson.cards)assert.ok(l6.includes('width="'+c.w+'" height="'+c.h+'" alt="'+c.alt+'"'),c.file);
 assert.match(l6,/BreadcrumbList[\s\S]*"name":"Baby"[\s\S]*"name":"9–12 Months"[\s\S]*"name":"First Actions & Body Parts"/);
});
test('lesson 7 follows the Toddler 1 spec with Try Together, Find It at Home and coming-soon next',()=>{
 checkLesson(l7,fwfhLesson);
 assert.ok(l7.includes('TODDLER 1 · LESSON 7'));
 assert.ok(l7.includes('TRY TOGETHER'));
 assert.ok(l7.includes('<h2>Little things to say.</h2>'));
 for(const p of fwfhLesson.tryTogether)assert.ok(l7.includes('<li>'+p+'</li>'),p);
 assert.ok(l7.includes('REAL-WORLD CONNECTION'));
 assert.ok(l7.includes('<h2>Find It at Home</h2>'));
 assert.ok(l7.includes(fwfhLesson.realWorld.copy));
 for(const p of fwfhLesson.realWorld.examples)assert.ok(l7.includes('<li>'+p+'</li>'),p);
 assert.ok(l7.includes('Every child develops differently'));
 assert.ok(l7.includes('Previous lesson'));
 assert.ok(l7.includes('href="/baby/9-12-months/first-actions-body-parts/"'));
 assert.ok(l7.includes('9–12 Months'));
 assert.ok(l7.includes('Next lesson'));
 assert.ok(l7.includes('href="/toddler/18-24-months/first-concepts-big-small-up-down/"'));
 assert.ok(l7.includes('18–24 Months'));
 const files=[...l7.matchAll(new RegExp(lessonsBase.replace(/\./g,'\\.')+'first-words-food-home-12-18-months/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(new Set(files).size,11,'each card present exactly once (bed card reserved: artwork never shipped)');
 assert.deepEqual([...new Set(files)],fwfhLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.match(l7,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"12–18 Months"[\s\S]*"name":"First Words: Food & Home"/);
});
test('lesson 8 follows the Toddler 2 spec with six concept pairs, Try Together, Practice Around the House and coming-soon next',()=>{
 checkLesson(l8,fcLesson);
 assert.ok(l8.includes('TODDLER 2 · LESSON 8'));
 assert.ok(l8.includes('TRY TOGETHER'));
 assert.ok(l8.includes('<h2>Little things to say.</h2>'));
 for(const p of fcLesson.tryTogether)assert.ok(l8.includes('<li>'+p+'</li>'),p);
 assert.ok(l8.includes('REAL-WORLD CONNECTION'));
 assert.ok(l8.includes('<h2>Practice Around the House</h2>'));
 assert.ok(l8.includes(fcLesson.realWorld.copy));
 for(const p of fcLesson.realWorld.examples)assert.ok(l8.includes('<li>'+p+'</li>'),p);
 assert.ok(l8.includes('Every child develops differently'));
 assert.ok(l8.includes('Previous lesson'));
 assert.ok(l8.includes('href="/toddler/12-18-months/first-words-food-home/"'));
 assert.ok(l8.includes('12–18 Months'));
 assert.ok(l8.includes('Next lesson'));
 assert.ok(l8.includes('href="/toddler/2-years/colors-and-shapes/"'));
 assert.ok(l8.includes('Age 2'));
 const files=[...l8.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'first-concepts-18-24-months/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(files.length,11,'grid shows each card exactly once (Out card reserved: the artwork never shipped)');
 assert.deepEqual([...new Set(files)],fcLesson.cards.map(c=>c.file.replace('.webp','')));
 for(const c of fcLesson.cards)assert.ok(l8.includes('width="'+c.w+'" height="'+c.h+'" alt="'+c.alt+'"'),c.file);
 for(const c of fcLesson.cards)assert.ok(!l8.includes('<figure class="lv-card"><span>'+c.concept),c.concept+' must never overlay the card image'); const concepts=fcLesson.cards.map(c=>c.concept);
 for(const [a,b] of [['Big','Small'],['Up','Down'],['Open','Closed'],['Full','Empty'],['One','Many']]){const i=concepts.indexOf(a);assert.ok(i>-1&&concepts[i+1]===b,a+' pairs with '+b);}
 assert.ok(concepts.includes('In'),'In card ships; Out is played off screen (no artwork was ever uploaded for it)');
 assert.match(l8,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"18–24 Months"[\s\S]*"name":"First Concepts"/);
});
test('lesson 9 (Colors & Shapes, Toddler 3) follows its spec with the interactive toddler class',()=>{
 assert.ok(l9.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/colors-and-shapes/"'));
 assert.ok(l9.includes('<title>Colors and Shapes for 2-Year-Olds | Kiddo.school</title>'));
 assert.ok(l9.includes('content="'+csLesson.description+'"'));
 assert.ok(l9.includes('<h1>Colors and Shapes for 2-Year-Olds</h1>'));
 assert.ok(l9.includes('TODDLER 3 · LESSON 9'));
 for(const [k,v] of csLesson.chips)assert.ok(l9.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok(l9.includes('<figure class="lesson-cover"><img src="'+csLesson.ogImage+'" width="1414" height="2000" alt="Colors and Shapes class for 2-year-olds at Kiddo School"'));
 assert.ok(l9.includes('TEACHER WELCOME'));
 assert.ok(l9.includes('Today we’re exploring colors and shapes! Let’s look, find and play together.'));
 assert.ok(l9.includes('id="learn-colors"'));
 assert.ok(l9.includes('id="play-colors"'));
 assert.ok(l9.includes('id="learn-shapes"'));
 assert.ok(l9.includes('id="play-shapes"'));
 assert.ok(l9.includes('id="find-match"'));
 assert.ok(l9.includes('TAKE IT OFF SCREEN'));
 assert.ok(l9.includes('<h2>Find colors and shapes around you.</h2>'));
 assert.ok(l9.includes('Can you find something red?'));
 assert.ok(l9.includes('A plate, a clock or a wheel is a good place to start.'));
 assert.ok(l9.includes('printable version of these hunts'));
 assert.ok(l9.includes('DOWNLOAD &amp; PRINT'));
 assert.ok(l9.includes('<h2>Download &amp; Print.</h2>'));
 assert.ok(l9.includes('Continue the class away from the screen with printable color cards, shape cards, matching activities and simple hunts to explore together.'));
 assert.ok(l9.includes('Colors &amp; Shapes Printable Activity Pack'));
 assert.ok(l9.includes('Age 2 · Toddler 3 · Think &amp; Talk'));
 assert.ok(l9.includes('href="/toddler/2-years/colors-and-shapes/print/"'));
 assert.ok(l9.includes('View Printable Pack'));
 assert.ok(l9.includes('data-tc-print-open="/toddler/2-years/colors-and-shapes/print/?print=1"'));
 assert.ok(l9.includes('Print Activity Pack'));
 assert.ok(!/download (the )?pdf/i.test(l9),'no fake PDF claims');
 assert.ok(l9.includes('Eight little steps'));
 assert.ok(l9.includes('<li><span>8</span> Download &amp; print</li>'));
 const packFiles=[...l9.matchAll(new RegExp('src="'+toddlerBase.replace(/\./g,'\\.')+'colors-and-shapes-age-2/printables/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.deepEqual([...new Set(packFiles)],csLesson.printables.pages.map(p=>p.file.replace('.webp','')));
 assert.equal(packFiles.length,8,'each printable referenced exactly once in the preview grid');
 for(const p of csLesson.printables.pages){
  assert.ok(l9.includes('width="1414" height="2000" alt="'+p.alt+'" loading="lazy"'),p.file);
  assert.ok(l9.includes('aria-label="Open full-size '+p.title+' page"'),p.file);
 }
 assert.ok(l9.includes('href="#printables"'));
 const printView=read('dist/toddler/2-years/colors-and-shapes/print/index.html');
 assert.ok(printView.includes('content="noindex,follow"'),'print view is noindex');
 assert.ok(printView.includes('<body class="print-view">'));
 assert.ok(printView.includes('<h1>Colors &amp; Shapes Printable Activity Pack</h1>'));
 assert.ok(printView.includes('data-tc-print-view'));
 for(const p of csLesson.printables.pages)assert.ok(printView.includes('alt="'+p.alt+'"'),p.file);
 const pvOrder=[...printView.matchAll(new RegExp('src="[^"]*printables/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.deepEqual(pvOrder,csLesson.printables.pages.map(p=>p.file.replace('.webp','')),'print view keeps exact page order');
 assert.ok(l9.includes('TEACHER NOTE'));
 assert.ok(l9.includes('Colors and shapes are everywhere. Keep naming the ones you notice together today.'));
 assert.ok(l9.includes('A NOTE FROM THE PRINCIPAL'));
 assert.ok(l9.includes('<h2>Class complete!</h2>'));
 assert.ok(l9.includes('Nice exploring colors and shapes together.'));
 assert.ok(l9.includes('<h2>Play and match.</h2>'));
 assert.ok(l9.includes('<h2>Tips for Parents</h2>'));
 for(const p of csLesson.howTo.paragraphs)assert.ok(l9.includes(p),p.slice(0,40));
 assert.ok(l9.includes('Age ranges are a guide'));
 assert.ok(l9.includes('guides, not tests or developmental deadlines'));
 assert.ok(l9.includes('Previous class'));
 assert.ok(l9.includes('href="/toddler/18-24-months/first-concepts-big-small-up-down/"'));
 assert.ok(l9.includes('href="/toddler/2-years/matching-and-sorting/"'));
 assert.ok(l9.includes('Next class'));
 assert.ok(!/6\/10|Score|Failed|Wrong!|Try again until you pass/.test(l9),'no competitive scoring language');
 const files=[...l9.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'colors-and-shapes-age-2/learning-cards/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.ok(files.length>=15,'all 15 learning cards present');
 assert.deepEqual([...new Set(files)],csLesson.cards.map(c=>c.file.replace('.webp','')));
 for(const c of csLesson.cards)assert.ok(l9.includes('width="'+c.w+'" height="'+c.h+'" alt="'+c.alt+'"'),c.file);
 assert.ok(l9.includes('data-tc-correct="true"'));
 assert.equal((l9.match(/data-tc-round/g)||[]).length,10);
 assert.equal((l9.match(/data-lesson-viewer/g)||[]).length,2,'two Learn viewers, no duplicate main viewer');
 assert.match(l9,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"Age 2"[\s\S]*"name":"Colors & Shapes"/);
 assert.ok(l9.includes('property="og:image" content="'+csLesson.ogImage+'"'));
 assert.ok(l9.includes('name="twitter:card" content="summary_large_image"'));
});
test('lesson 10 (Matching & Sorting, Toddler 4) follows its spec with the interactive toddler class',()=>{
 assert.ok(l10.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/matching-and-sorting/"'));
 assert.ok(l10.includes('<title>Matching and Sorting for 2-Year-Olds | Kiddo.school</title>'));
 assert.ok(l10.includes('content="'+msLesson.description+'"'));
 assert.equal(msLesson.description,'Explore matching and sorting with your 2-year-old through simple visual activities for colors, shapes, everyday objects and things that belong together.');
 assert.ok(l10.includes('<h1>Matching and Sorting for 2-Year-Olds</h1>'));
 assert.ok(l10.includes('TODDLER 4 · LESSON 10'));
 for(const [k,v] of msLesson.chips)assert.ok(l10.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok(l10.includes('<figure class="lesson-cover"><img src="'+msLesson.ogImage+'" width="1414" height="2000" alt="Matching and Sorting class for 2-year-olds at Kiddo School"'));
 assert.ok(l10.includes('TEACHER WELCOME'));
 assert.ok(l10.includes('Today we’re going to find things that match and things that are different. Let’s look together!'));
 for(const id of ['same-different','find-match','sort-together','belongs','different-one'])assert.ok(l10.includes('id="'+id+'"'),id);
 assert.ok(l10.includes('LEARN · SAME &amp; DIFFERENT'));
 assert.ok(l10.includes('<h2>Same and different.</h2>'));
 assert.ok(l10.includes('<h2>Find the match.</h2>'));
 assert.ok(l10.includes('<h2>Sorting colors and shapes.</h2>'));
 assert.ok(l10.includes('<h2>What belongs together?</h2>'));
 assert.ok(l10.includes('<h2>Find the different one.</h2>'));
 assert.ok(l10.includes('TAKE IT OFF SCREEN'));
 assert.ok(l10.includes('<h2>Take it off screen.</h2>'));
 assert.ok(l10.includes('Find two matching socks.'));
 assert.ok(l10.includes('Find one object that is different from the others.'));
 assert.ok(!l10.includes('DOWNLOAD &amp; PRINT'),'no printables section without real printable assets');
 assert.ok(!l10.includes('print/'),'no invented print view links');
 assert.ok(!/download (the )?pdf/i.test(l10),'no fake PDF claims');
 assert.ok(l10.includes('Seven little steps'));
 assert.ok(l10.includes('<li><span>7</span> Take it off screen</li>'));
 assert.ok(l10.includes('TEACHER NOTE'));
 assert.ok(l10.includes('Matching happens everywhere. Try noticing things that are the same, different or belong together during your day.'));
 assert.ok(l10.includes('A NOTE FROM THE PRINCIPAL'));
 assert.ok(l10.includes('There’s no need to turn matching into a test.'));
 assert.ok(l10.includes('<h2>Class complete!</h2>'));
 assert.ok(l10.includes('Nice matching and sorting together.'));
 assert.ok(l10.includes('<h2>Tips for Parents</h2>'));
 for(const p of msLesson.howTo.paragraphs)assert.ok(l10.includes(p),p.slice(0,40));
 assert.ok(l10.includes('Age ranges are a guide'));
 assert.ok(l10.includes('guides, not tests or developmental deadlines'));
 assert.ok(l10.includes('Previous class'));
 assert.ok(l10.includes('href="/toddler/2-years/colors-and-shapes/"'));
 assert.ok(l10.includes('Colors &amp; Shapes'));
 assert.ok(l10.includes('href="/toddler/2-years/animals-and-sounds/"'),'next class links to lesson 11');
 assert.ok(l10.includes('Next class'));
 assert.ok(l10.includes('Animals &amp; Sounds'));
 assert.ok(!l10.includes('Coming soon'),'no invented next class placeholder');
 assert.ok(!/6\/10|Score|Failed|Wrong!|Try again until you pass/.test(l10),'no competitive scoring language');
 const files=[...l10.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'matching-and-sorting-age-2/learning-cards/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.ok(files.length>=15,'all 15 learning cards present');
 assert.deepEqual([...new Set(files)],msLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.ok(l10.includes('src="'+msLesson.ogImage+'"'),'cover referenced exactly from its R2 path');
 for(const c of msLesson.cards)assert.ok(l10.includes('width="'+c.w+'" height="'+c.h+'" alt="'+c.alt+'"'),c.file);
 for(const alt of ['Two matching red balls for a toddler same-and-match activity','Apple, banana, car and shoe for a toddler grouping activity','Three bananas and one apple for a toddler odd-one-out activity'])assert.ok(l10.includes('alt="'+alt+'"'),alt);
 assert.ok(l10.includes('data-tc-correct="true"'));
 assert.equal((l10.match(/data-tc-round/g)||[]).length,7,'4 find-the-match + 2 belongs + 1 odd-one-out rounds');
 assert.equal((l10.match(/data-lesson-viewer/g)||[]).length,2,'two Learn viewers, no duplicate main viewer');
 assert.equal((l10.match(/class="tc-choice tc-num"/g)||[]).length,16,'12 find-the-match + 4 odd-one-out position buttons');
 for(const label of ['The red ball','The blue square','The circle','The triangle','The apple'])assert.ok(l10.includes('aria-label="'+label+'"'),label);
 assert.ok(l10.includes('Can you find the red one?'));
 assert.ok(l10.includes('Which one matches the circle?'));
 assert.ok(l10.includes('Which one is different?'));
 assert.ok(l10.includes('Which picture shows the fruit?'));
 assert.match(l10,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"Age 2"[\s\S]*"name":"Matching & Sorting"/);
 assert.ok(l10.includes('property="og:image" content="'+msLesson.ogImage+'"'));
 assert.ok(l10.includes('name="twitter:card" content="summary_large_image"'));
 assert.ok(l10.includes('"learningResourceType":"Interactive toddler class"'));
});
test('lesson 11 (Animals & Sounds, Toddler 5) follows its spec with the interactive toddler class',()=>{
 assert.ok(l11.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/animals-and-sounds/"'));
 assert.ok(l11.includes('<title>Animals and Sounds for 2-Year-Olds | Kiddo.school</title>'));
 assert.ok(l11.includes('content="'+anLesson.description+'"'));
 assert.equal(anLesson.description,'Meet twenty animals and make their sounds together. Farm friends, wild animals and two gentle tap games, made for two-year-olds and their grown-ups.');
 assert.ok(l11.includes('<h1>Animals and Sounds for 2-Year-Olds</h1>'));
 assert.ok(l11.includes('TODDLER 5 · LESSON 11'));
 for(const [k,v] of anLesson.chips)assert.ok(l11.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok(l11.includes('<figure class="lesson-cover"><img src="'+anLesson.ogImage+'" width="1414" height="2000" alt="Animals and Sounds class for 2-year-olds at Kiddo School"'));
 assert.ok(l11.includes('Moo, woof, quack!'));
 assert.ok(l11.includes('Start Class <span aria-hidden="true">↓</span>'),'simple Start Class button per writing style');
 assert.ok(!l11.includes('Start Today’s Class'),'style: no verbose start button');
 assert.ok(l11.includes('TEACHER WELCOME'));
 assert.ok(l11.includes('Let’s meet some animals! Can you make their sounds with me?'));
 for(const id of ['farm-animals','who-says','wild-animals','find-animal','more-animals'])assert.ok(l11.includes('id="'+id+'"'),id);
 assert.ok(l11.includes('LEARN · FARM ANIMALS'));
 assert.ok(l11.includes('<h2>Meet the farm animals.</h2>'));
 assert.ok(l11.includes('<h2>Who says moo?</h2>'));
 assert.ok(l11.includes('<h2>Meet the wild animals.</h2>'));
 assert.ok(l11.includes('<h2>Find the animal.</h2>'));
 assert.ok(l11.includes('<h2>A few more friends.</h2>'));
 assert.ok(l11.includes('TAKE IT OFF SCREEN'));
 assert.ok(l11.includes('<h2>Animals are everywhere.</h2>'));
 assert.ok(l11.includes('Spot a bird outside? Listen together.'));
 assert.ok(!l11.includes('DOWNLOAD &amp; PRINT'),'no printables section without real printable assets');
 assert.ok(!l11.includes('print/'),'no invented print view links');
 assert.ok(!/download (the )?pdf/i.test(l11),'no fake PDF claims');
 assert.ok(l11.includes('Seven little steps'));
 assert.ok(l11.includes('<li><span>7</span> Take it off screen</li>'));
 assert.ok(l11.includes('Meet the animals <span aria-hidden="true">↓</span>'),'welcome CTA uses warm simple wording');
 assert.ok(l11.includes('TEACHER NOTE'));
 assert.ok(l11.includes('If your child can’t make a sound yet, make it for them. Listening is learning too.'));
 assert.ok(l11.includes('A NOTE FROM THE PRINCIPAL'));
 assert.ok(l11.includes('You don’t need to cover every card today. Follow what your child enjoys.'));
 assert.ok(l11.includes('<h2>Class complete!</h2>'));
 assert.ok(l11.includes('Nice animal sounds together.'));
 assert.ok(l11.includes('<h2>Tips for Parents</h2>'));
 for(const p of anLesson.howTo.paragraphs)assert.ok(l11.includes(p),p.slice(0,40));
 assert.ok(l11.includes('Age ranges are a guide'));
 assert.ok(l11.includes('guides, not tests or developmental deadlines'));
 assert.ok(l11.includes('Previous class'));
 assert.ok(l11.includes('href="/toddler/2-years/matching-and-sorting/"'));
 assert.ok(l11.includes('Matching &amp; Sorting'));
 assert.ok(l11.includes('href="/toddler/2-years/vehicles-and-sounds/"'),'next class links to lesson 12');
 assert.ok(l11.includes('Next class'));
 assert.ok(l11.includes('Vehicles &amp; Sounds'));
 assert.ok(l11.includes('href="/learning-path/"'));
 assert.ok(!l11.includes('Coming soon'),'no invented next class');
 assert.ok(!/6\/11|Score|Failed|Wrong!|Try again until you pass/.test(l11),'no competitive scoring language');
 const files=[...l11.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'animals-and-sounds-age-2/(\\d{2}-[a-z-]+)\\.webp','g'))].map(m=>m[1]);
 assert.ok(files.length>=20,'all 20 learning cards present');
 assert.deepEqual([...new Set(files)],anLesson.cards.map(c=>c.file.replace('.webp','')));
 assert.ok(l11.includes('src="'+anLesson.ogImage+'"'),'cover referenced exactly from its R2 path');
 for(const c of anLesson.cards)assert.ok(l11.includes('width="'+c.w+'" height="'+c.h+'" alt="'+c.alt+'"'),c.file);
 for(const alt of ['A dog saying woof for a toddler animal sounds activity','An elephant trumpeting for a toddler animal sounds activity','A donkey saying hee-haw for a toddler animal sounds activity'])assert.ok(l11.includes('alt="'+alt+'"'),alt);
 assert.ok(l11.includes('data-tc-correct="true"'));
 assert.equal((l11.match(/data-tc-round/g)||[]).length,8,'4 who-says + 4 find-the-animal rounds');
 assert.equal((l11.match(/data-lesson-viewer/g)||[]).length,3,'three Learn viewers (farm, wild, more)');
 assert.equal((l11.match(/class="tc-choice"/g)||[]).length,24,'8 rounds × 3 real image-choice buttons');
 assert.ok(!l11.includes('class="tc-choice tc-num"'),'no numbered position buttons — every card is its own image');
 for(const label of ['The cow','The duck','The dog','The cat','The lion','The elephant','The owl','The snake'])assert.ok(l11.includes('aria-label="'+label+'"'),label);
 assert.ok(l11.includes('Who says moo?'));
 assert.ok(l11.includes('Who says quack?'));
 assert.ok(l11.includes('Find the lion.'));
 assert.ok(l11.includes('Find the snake.'));
 assert.match(l11,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"Age 2"[\s\S]*"name":"Animals & Sounds"/);
 assert.ok(l11.includes('property="og:image" content="'+anLesson.ogImage+'"'));
 assert.ok(l11.includes('name="twitter:card" content="summary_large_image"'));
 assert.ok(l11.includes('"learningResourceType":"Interactive toddler class"'));
});
test('lesson 12 (Vehicles & Sounds, Toddler 6) follows its spec with the interactive toddler class',()=>{
 assert.ok(l12.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/vehicles-and-sounds/"'));
 assert.ok(l12.includes('<title>Vehicles and Sounds for 2-Year-Olds | Kiddo.school</title>'));
 assert.ok(l12.includes('content="'+vhLesson.description+'"'));
 assert.equal(vhLesson.description,'Explore cars, buses, trains and more with colorful vehicle cards, simple sound games and playful activities for 2-year-olds.');
 assert.ok(l12.includes('<h1>Vehicles and Sounds for 2-Year-Olds</h1>'));
 assert.ok(l12.includes('TODDLER 6 · LESSON 12'));
 for(const [k,v] of vhLesson.chips)assert.ok(l12.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok(l12.includes('<figure class="lesson-cover"><img src="'+vhLesson.ogImage+'" width="2000" height="1294" alt="Vehicles and Sounds class for 2-year-olds at Kiddo School"'));
 assert.ok(l12.includes('Beep beep! Vroom! Choo choo!'));
 assert.ok(l12.includes('Start Class <span aria-hidden="true">↓</span>'),'simple Start Class button per writing style');
 assert.ok(!l12.includes('Start Today’s Class'),'style: no verbose start button');
 assert.ok(l12.includes('TEACHER WELCOME'));
 assert.ok(l12.includes('Let’s meet some vehicles! Can you make their sounds with me?'));
 for(const id of ['meet-the-vehicles','make-the-sounds','working-vehicles','who-makes-this-sound','sky-vehicles','find-the-vehicle','where-does-it-go','off-screen','printables'])assert.ok(l12.includes('id="'+id+'"'),id);
 assert.ok(l12.includes('<h2>Meet the vehicles.</h2>'));
 assert.ok(l12.includes('<h2>Make the sounds.</h2>'));
 assert.ok(l12.includes('<h2>Vehicles that work.</h2>'));
 assert.ok(l12.includes('<h2>Who makes this sound?</h2>'));
 assert.ok(l12.includes('<h2>Boats, planes and a rocket.</h2>'));
 assert.ok(l12.includes('<h2>Find the vehicle.</h2>'));
 assert.ok(l12.includes('<h2>Where does it go?</h2>'));
 assert.ok(l12.includes('TAKE IT OFF SCREEN'));
 assert.ok(l12.includes('<h2>Vehicle hunt.</h2>'));
 assert.ok(l12.includes('Look out the window or take a walk. Spot a car, bus or truck and name it together.'));
 assert.ok(l12.includes('Count the buses you see.'));
 assert.ok(l12.includes('Spot something that flies.'));
 assert.ok(l12.includes('PRINT THE CARDS'));
 assert.ok(l12.includes('<h2>Print the vehicle cards.</h2>'));
 assert.ok(l12.includes('Print the cards for vehicle hunts, matching and sound games.'));
 assert.ok(l12.includes('href="/toddler/2-years/vehicles-and-sounds/print/"'));
 assert.ok(l12.includes('View Printable Cards'));
 assert.ok(l12.includes('data-tc-print-open="/toddler/2-years/vehicles-and-sounds/print/?print=1"'));
 assert.ok(l12.includes('Print Cards'));
 assert.ok(!/download (the )?pdf/i.test(l12),'no fake PDF claims');
 assert.ok(l12.includes('Ten little steps'));
 assert.ok(l12.includes('<li><span>10</span> Print the cards</li>'));
 assert.ok(l12.includes('TEACHER NOTE'));
 assert.ok(l12.includes('Keep naming the vehicles you notice together today.'));
 assert.ok(l12.includes('A NOTE FROM THE PRINCIPAL'));
 assert.ok(l12.includes('Your child doesn’t need to learn every card today. Follow what catches their interest.'));
 assert.ok(l12.includes('<h2>Class complete!</h2>'));
 assert.ok(l12.includes('Nice beeps, toots and choo choos together.'));
 assert.ok(l12.includes('<h2>Tips for Parents</h2>'));
 for(const p of vhLesson.howTo.paragraphs)assert.ok(l12.includes(p),p.slice(0,40));
 assert.ok(l12.includes('Age ranges are a guide'));
 assert.ok(l12.includes('Go at your child’s pace'),'short safety line, once only, per spec');
 assert.equal((l12.match(/Age ranges are a guide/g)||[]).length,1,'age-guide line appears exactly once on the page');
 assert.ok(l12.includes('Previous class'));
 assert.ok(l12.includes('href="/toddler/2-years/animals-and-sounds/"'));
 assert.ok(l12.includes('Animals &amp; Sounds'));
 assert.ok(l12.includes('href="/toddler/2-years/emotions-and-feelings/"'),'next class links to lesson 13');
 assert.ok(l12.includes('Next class'));
 assert.ok(l12.includes('Emotions &amp; Feelings'));
 assert.ok(!l12.includes('Coming soon'),'no invented next class');
 assert.ok(!/Score|Failed|Wrong!|Try again until you pass/.test(l12),'no competitive scoring language');
 assert.ok(!l12.includes('vehicles-and-sounds-age-2/learning-cards/'),'NO learning-cards subfolder requests');
 assert.ok(!l12.includes('printables/'),'no printables folder — digital and print share the SAME card assets');
 const files=[...l12.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'vehicles-and-sounds-age-2/([\\w-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal([...new Set(files)].length,21,'all 21 R2 files referenced (cover + 20 cards)');
 assert.deepEqual([...new Set(files)].sort(),['cover',...vhLesson.cards.map(c=>c.file.replace('.webp',''))].sort());
 assert.ok(l12.includes('src="'+vhLesson.ogImage+'"'),'cover referenced exactly from its R2 path');
 for(const c of vhLesson.cards)assert.ok(l12.includes('alt="'+c.alt+'"'),c.file);
 assert.ok(l12.includes('alt="Cartoon car learning card labeled Car with Beep beep"'));
 assert.ok(l12.includes('alt="Kick scooter learning card labeled Scooter with Zoom"'),'scooter alt uses the exact spec wording');
 for(const c of vhLesson.cards)assert.ok(l12.includes('width="2000" height="1294"'),'landscape cards keep true dimensions');
 assert.ok(l12.includes('data-tc-correct="true"'));
 assert.equal((l12.match(/data-tc-round/g)||[]).length,13,'6 who-makes + 4 find + 3 where-goes rounds');
 assert.equal((l12.match(/data-lesson-viewer/g)||[]).length,4,'four viewers (meet, sounds, working, sky)');
 assert.equal((l12.match(/class="tc-choice"/g)||[]).length,39,'13 rounds × 3 real image-choice buttons');
 assert.ok(!l12.includes('class="tc-choice tc-num"'),'no numbered position buttons — every card is its own image');
 for(const label of ['The car','The train','The ship','The helicopter','The bicycle','The tractor','The boat','The airplane'])assert.ok(l12.includes('aria-label="'+label+'"'),label);
 for(const q of ['Who goes choo choo?','Who goes beep beep?','Who goes vroom?','Who goes toot toot?','Who goes whirr?','Who goes ring ring?','Find the bus.','Where is the airplane?','Can you find the tractor?','Find the boat.','Which one goes on tracks?','Which one flies in the sky?','Which one goes on water?'])assert.ok(l12.includes(q),q);
 for(const r of vhLesson.interactive.sections.filter(s=>s.type==='play').flatMap(s=>s.rounds)){
  const tail=l12.split('data-tc-ask="'+r.ask+'"')[1];
  const cut=tail.indexOf('data-tc-round');
  const roundHtml=cut===-1?tail:tail.slice(0,cut);
  assert.equal((roundHtml.match(/data-tc-correct="true"/g)||[]).length,1,r.ask+' has exactly one correct choice');
  for(const c of r.choices)assert.ok(roundHtml.includes('alt="'+vhLesson.cards.find(x=>x.file===c.file).alt+'"'),r.ask+' shows '+c.name);
 }
 assert.match(l12,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"Age 2"[\s\S]*"name":"Vehicles & Sounds"/);
 assert.ok(l12.includes('property="og:image" content="'+vhLesson.ogImage+'"'));
 assert.ok(l12.includes('name="twitter:card" content="summary_large_image"'));
 assert.ok(l12.includes('"learningResourceType":"Interactive toddler class"'));
 const pv=read('dist/toddler/2-years/vehicles-and-sounds/print/index.html');
 assert.ok(pv.includes('content="noindex,follow"'),'print view is noindex');
 assert.ok(pv.includes('<body class="print-view">'));
 assert.ok(pv.includes('<h1>Vehicle Learning Cards</h1>'));
 assert.ok(pv.includes('data-tc-print-view'));
 assert.ok(pv.includes('Back to class'));
 assert.ok(!pv.includes('vehicles-and-sounds-age-2/learning-cards/'),'print view uses the same direct R2 path, no subfolder');
 assert.ok(!pv.includes('printables/'),'no printables folder anywhere');
 const pvFiles=[...pv.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'vehicles-and-sounds-age-2/([\\w-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(pvFiles.length,20,'each card referenced exactly once in the print view');
 assert.deepEqual([...new Set(pvFiles)],vhLesson.cards.map(c=>c.file.replace('.webp','')),'print view uses the SAME 20 card assets, in card order');
 assert.equal((pv.match(/class="tc-print-sheet"/g)||[]).length,10,'ten sheets — two cards per printed page');
 assert.ok(!pv.includes('loading="lazy"'),'print images load eagerly for printing');
});
test('lesson 13 (Emotions & Feelings, Toddler 7) follows its spec with the interactive toddler class',()=>{
 assert.ok(l13.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/emotions-and-feelings/"'));
 assert.ok(l13.includes('<title>Emotions &amp; Feelings for 2-Year-Olds | Kiddo.school</title>'));
 assert.ok(l13.includes('content="'+emLesson.description+'"'));
 assert.equal(emLesson.description,'Help your 2-year-old explore feelings with simple emotion cards, face-matching games and printable activities you can use together.');
 assert.ok(l13.includes('<h1>Emotions &amp; Feelings for 2-Year-Olds</h1>'));
 assert.ok(l13.includes('TODDLER 7 · LESSON 13'));
 for(const [k,v] of emLesson.chips)assert.ok(l13.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok(l13.includes('<figure class="lesson-cover"><img src="'+emLesson.ogImage+'" width="2000" height="1414" alt="Emotions and Feelings class for 2-year-olds at Kiddo School"'));
 assert.ok(l13.includes('Happy, sad, angry, excited — little feelings can have big names.'));
 assert.ok(l13.includes('Start Class <span aria-hidden="true">↓</span>'),'simple Start Class button per writing style');
 assert.ok(!l13.includes('Start Today’s Class'),'style: no verbose start button');
 assert.ok(l13.includes('TEACHER WELCOME'));
 assert.ok(l13.includes('Let’s look at some faces. How do they feel?'));
 for(const id of ['meet-the-feelings','how-do-they-feel','find-the-feeling','faces-and-feelings','what-can-we-do','off-screen','printables'])assert.ok(l13.includes('id="'+id+'"'),id);
 assert.ok(l13.includes('<h2>Meet the feelings.</h2>'));
 assert.ok(l13.includes('<h2>How do they feel?</h2>'));
 assert.ok(l13.includes('<h2>Find the feeling.</h2>'));
 assert.ok(l13.includes('<h2>Faces &amp; feelings.</h2>'));
 assert.ok(l13.includes('<h2>What can we do?</h2>'));
 assert.ok(l13.includes('TAKE IT OFF SCREEN'));
 assert.ok(l13.includes('<h2>Feelings in our day.</h2>'));
 assert.ok(l13.includes('Name feelings when they naturally come up today.'));
 assert.ok(l13.includes('“You’re smiling. You look happy!”'));
 assert.ok(l13.includes('“That was frustrating.”'));
 assert.ok(l13.includes('Make silly faces together in a mirror.'));
 assert.ok(!l13.includes('good feelings')&&!l13.includes('naughty'),'feelings stay neutral — no good/bad teaching');
 assert.ok(!/stop (crying|feeling)/i.test(l13),'no shaming or suppression language');
 assert.ok(!/prevent tantrums|fix behavior|raise IQ|improve mental health/i.test(l13),'no outcome promises');
 assert.ok(l13.includes('PRINT THE CARDS'));
 assert.ok(l13.includes('<h2>Print the feeling cards.</h2>'));
 assert.ok(l13.includes('Print the cards for simple feeling games and conversations.'));
 assert.ok(l13.includes('href="/toddler/2-years/emotions-and-feelings/print/"'));
 assert.ok(l13.includes('View Printable Cards'));
 assert.ok(l13.includes('data-tc-print-open="/toddler/2-years/emotions-and-feelings/print/?print=1"'));
 assert.ok(l13.includes('Print Cards'));
 assert.ok(!/download (the )?pdf/i.test(l13),'no fake PDF claims');
 assert.ok(l13.includes('Eight little steps'));
 assert.ok(l13.includes('<li><span>8</span> Print the cards</li>'));
 assert.ok(l13.includes('TEACHER NOTE'));
 assert.ok(l13.includes('When the next wobble arrives — and it will — you both have words for it now.'));
 assert.ok(l13.includes('A NOTE FROM THE PRINCIPAL'));
 assert.ok(l13.includes('Your child doesn’t need to name every feeling. You’re simply giving them words they can grow into.'));
 assert.ok(l13.includes('<h2>Class complete!</h2>'));
 assert.ok(l13.includes('All those feelings together — happy, sad, silly and brave.'));
 assert.ok(l13.includes('<h2>Tips for Parents</h2>'));
 for(const p of emLesson.howTo.paragraphs)assert.ok(l13.includes(p),p.slice(0,40));
 assert.ok(l13.includes('Age ranges are a guide'));
 assert.ok(l13.includes('Go at your child’s pace'),'short safety line, once only, per spec');
 assert.equal((l13.match(/Age ranges are a guide/g)||[]).length,1,'age-guide line appears exactly once on the page');
 assert.ok(l13.includes('Previous class'));
 assert.ok(l13.includes('href="/toddler/2-years/vehicles-and-sounds/"'));
 assert.ok(l13.includes('Vehicles &amp; Sounds'));
 assert.ok(!l13.includes('Coming soon'),'no invented next class');
 assert.ok(!/Score|Failed|Wrong!|Try again until you pass/.test(l13),'no competitive scoring language');
 assert.ok(!l13.includes('emotions-and-feelings-age-2/learning-cards/'),'NO learning-cards subfolder requests');
 assert.ok(!l13.includes('printables/'),'no printables folder — digital and print share the SAME card assets');
 const files=[...l13.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'emotions-and-feelings-age-2/([\\w-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal([...new Set(files)].length,21,'all 21 R2 files referenced (cover + 20 feeling cards)');
 assert.deepEqual([...new Set(files)].sort(),['cover',...emLesson.cards.map(c=>c.file.replace('.webp',''))].sort());
 assert.ok(l13.includes('src="'+emLesson.ogImage+'"'),'cover referenced exactly from its R2 path');
 for(const c of emLesson.cards)assert.ok(l13.includes('alt="'+c.alt+'"'),c.file);
 assert.ok(l13.includes('alt="2D illustrated child showing a mild hurt feeling"'),'hurt alt uses the exact spec wording');
 assert.ok(l13.includes('alt="2D illustrated child giving a friendly wave"'),'friendly alt uses the exact spec wording');
 assert.ok(l13.includes('alt="2D illustration showing a child being kind and helpful"'),'kind alt uses the exact spec wording');
 assert.ok(l13.includes('alt="2D illustrated child showing bravery by trying"'),'brave alt uses the exact spec wording');
 for(const c of emLesson.cards)assert.ok(l13.includes('width="2000" height="1414"'),'landscape cards keep true dimensions');
 const specData=[['Happy','I feel happy!'],['Sad','I feel sad.'],['Angry','I feel angry.'],['Scared','I feel scared.'],['Surprised','Oh!'],['Excited','I’m excited!'],['Tired','I’m tired.'],['Calm','I feel calm.'],['Shy','I feel shy.'],['Silly','I feel silly!'],['Proud','I did it!'],['Worried','I’m worried.'],['Frustrated','This is hard.'],['Confused','Hmm?'],['Bored','I’m bored.'],['Hurt','Ouch!'],['Loved','I feel loved.'],['Friendly','Hello!'],['Kind','I can help.'],['Brave','I can try.']];
 assert.deepEqual(emLesson.cards.map(c=>[c.name,c.phrase]),specData,'card names and phrases match the spec verbatim, in order');
 assert.ok(l13.includes('data-tc-correct="true"'));
 assert.equal((l13.match(/data-tc-round/g)||[]).length,10,'5 how-do-they-feel + 5 find-the-feeling rounds');
 assert.equal((l13.match(/data-lesson-viewer/g)||[]).length,2,'two viewers (meet the feelings, faces & feelings)');
 assert.equal((l13.match(/class="tc-choice"/g)||[]).length,24,'10 rounds × 2–3 real image-choice buttons');
 assert.ok(!l13.includes('class="tc-choice tc-num"'),'no numbered position buttons — every choice is its own image');
 const matchSect=emLesson.interactive.sections.find(s=>s.id==='how-do-they-feel');
 const playSect=emLesson.interactive.sections.find(s=>s.id==='find-the-feeling');
 assert.deepEqual(matchSect.rounds.map(r=>r.choices.findIndex(c=>c.correct)+1),[1,2,1,2,2],'match positions vary');
 assert.deepEqual(playSect.rounds.map(r=>r.choices.findIndex(c=>c.correct)+1),[2,1,2,1,2],'play positions vary');
 for(const s of emLesson.interactive.sections.filter(x=>x.rounds))for(const r of s.rounds)for(const c of r.choices)assert.ok(emLesson.cards.find(x=>x.file===c.file),'every choice is a real class card: '+c.name);
 const segs=l13.split('<div class="tc-round').slice(1);
 assert.equal(segs.length,10);
 for(const [i,seg] of segs.entries())assert.equal((seg.match(/data-tc-correct="true"/g)||[]).length,1,'round '+(i+1)+' has exactly one correct choice');
 for(const label of ['The happy face','The sad face','The angry face','The calm face','The scared face','The excited face','The tired face','The silly face','The worried face','The proud face'])assert.ok(l13.includes('aria-label="'+label+'"'),label);
 for(const q of ['How do they feel?','Find happy.','Where is sad?','Can you find tired?','Find surprised!','Where is calm?'])assert.ok(l13.includes(q),q);
 for(const phrase of ['Want a hug?','Let’s slow down together.','Stay close.','Let’s try together.','Maybe it’s time for a rest.'])assert.ok(l13.includes(phrase),'What Can We Do phrase: '+phrase);
 for(const feeling of ['Sad','Angry','Scared','Frustrated','Tired'])assert.ok(l13.includes('<h3>'+feeling+'</h3>'),'guide row for '+feeling);
 assert.match(l13,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"Age 2"[\s\S]*"name":"Emotions & Feelings"/);
 assert.ok(l13.includes('property="og:image" content="'+emLesson.ogImage+'"'));
 assert.ok(l13.includes('name="twitter:card" content="summary_large_image"'));
 assert.ok(l13.includes('"learningResourceType":"Interactive toddler class"'));
 assert.ok(emLesson.schema.keywords.includes('printable emotion cards')&&emLesson.schema.keywords.includes('feelings for toddlers'),'parent search intents covered in schema keywords');
 assert.ok(l13pv.includes('content="noindex,follow"'),'print view is noindex');
 assert.ok(l13pv.includes('<body class="print-view">'));
 assert.ok(l13pv.includes('PRINTABLE FEELING CARDS'));
 assert.ok(l13pv.includes('<h1>Feelings Learning Cards</h1>'));
 assert.ok(l13pv.includes('data-tc-print-view'));
 assert.ok(l13pv.includes('Back to class'));
 assert.ok(!l13pv.includes('emotions-and-feelings-age-2/learning-cards/'),'print view uses the same direct R2 path, no subfolder');
 assert.ok(!l13pv.includes('printables/'),'no printables folder anywhere');
 const pvFiles=[...l13pv.matchAll(new RegExp(toddlerBase.replace(/\./g,'\\.')+'emotions-and-feelings-age-2/([\\w-]+)\\.webp','g'))].map(m=>m[1]);
 assert.equal(pvFiles.length,20,'each card referenced exactly once in the print view');
 assert.deepEqual([...new Set(pvFiles)],emLesson.cards.map(c=>c.file.replace('.webp','')),'print view uses the SAME 20 card assets, in card order');
 assert.equal((l13pv.match(/class="tc-print-sheet"/g)||[]).length,10,'ten sheets — two cards per printed page');
 assert.ok(!l13pv.includes('loading="lazy"'),'print images load eagerly for printing');
});
test('circle time 1 (Hello School!) follows its spec with the one-moment session runner',()=>{
 assert.ok(ct1.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/circle-time/hello-school/"'));
 assert.ok(ct1.includes('<title>Circle Time for 2-Year-Olds: Hello School! | Kiddo.school</title>'));
 assert.ok(ct1.includes('content="Join a short Circle Time for 2-year-olds with movement, simple directions, a tiny story and an off-screen activity to do together."'),'exact spec meta description');
 assert.ok(ct1.includes('<h1>Hello School! Circle Time</h1>'),'spec H1');
 assert.ok(ct1.includes('CIRCLE TIME 1 · AGE 2'));
 for(const [k,v] of [['Age','2 Years'],['Class','Circle Time 1'],['Duration','5–8 minutes']])assert.ok(ct1.includes('<strong>'+k+'</strong> '+v),k);
 assert.ok(ct1.includes('Start Circle Time'));
 assert.ok(ct1.includes('Read the prompts aloud and do them together.'),'the one parent note');
 assert.equal((ct1.match(/Read the prompts aloud and do them together\./g)||[]).length,1,'parent note appears exactly once');
 assert.ok(ct1.includes('property="og:image" content="https://pub-f2fcb7c9b45a496cbeefef18dbba0ec0.r2.dev/circle-time/age-2/hello-school/cover.webp"'),'cover.webp is the social image');
 assert.ok(ct1.includes('name="twitter:card" content="summary_large_image"'));
 for(const [f,alt] of [
  ['cover.webp','Kiddo School teacher welcoming children to Circle Time'],
  ['01-hello-and-move.webp','Teacher and young children moving together during Circle Time'],
  ['02-listen-and-do.webp','Teacher and children doing a simple listening and movement activity'],
  ['03-story-time.webp','Young child arriving at school with a backpack and greeting the teacher'],
  ['04-goodbye.webp','Teacher and children waving goodbye at the end of Circle Time']])assert.ok(ct1.includes('alt="'+alt+'"'),'spec alt for '+f);
 const files=[...ct1.matchAll(/circle-time\/age-2\/hello-school\/([\w-]+)\.webp/g)].map(m=>m[1]);
 assert.equal([...new Set(files)].length,5,'exactly the five spec scene images');
 assert.deepEqual([...new Set(files)].sort(),['01-hello-and-move','02-listen-and-do','03-story-time','04-goodbye','cover']);
 assert.ok(!ct1.includes('learning-cards/')&&!ct1.includes('printables/')&&!ct1.includes('.r2.dev/flashcards/'),'NO flashcard, learning-card or printable assets (footer nav link aside)');
 assert.equal((ct1.match(/data-ct-step="/g)||[]).length,8,'eight moments in the session');
 for(const id of ['hello','rhythm','copy','listen','faces','story','rug','goodbye'])assert.ok(ct1.includes('data-ct-step="'+id+'"'),id);
 assert.equal((ct1.match(/data-ct-dot/g)||[]).length,9,'eight dots plus their container');
 for(const h2 of ['<h2>Hello &amp; Move</h2>','<h2>Listen &amp; Do</h2>','<h2>Story Time</h2>','<h2>Off the Rug</h2>'])assert.ok(ct1.includes(h2),h2);
 for(const line of ['Hi! Come sit with me. Ready?','I’m Ready','data-ct-rhythm','Clap, clap, wave!','>Again<','Touch your head.','Clap your hands.','Stomp your feet.','Reach up high.','Sit down.','Listen carefully. Can you do it?','Wave!','Point up!','Touch your toes!','Give someone a high five!','Let’s make some faces.','Make a happy face!','Make a silly face!','Show me sleepy.','Give me a big smile!','A little child packed a school bag.','They came to school.','The teacher waved. “Hello!”','The child waved back. It was time to learn and play.','Part 1 of 4','Can you find your favorite book?','Go get it and bring it back!','I Found One!','>Skip<','Take your time.','Great! You brought a book.','That was fun. See you next time!','Circle Time Complete'])assert.ok(ct1.includes(line),line);
 assert.ok(ct1.includes('data-ct-next hidden>I’m Ready</button>'),'real button, hidden until JS');
 assert.ok(ct1.includes('data-ct-replay hidden'),'Again replays the visual cue');
 assert.ok(ct1.includes('data-ct-found hidden')&&ct1.includes('data-ct-skip hidden'),'I Found One! and Skip both exist');
 assert.ok(ct1.includes('data-ct-back hidden'),'story Previous exists');
 assert.ok(ct1.includes('aria-live="polite"'),'step announcer');
 assert.ok(ct1.includes('— Your Kiddo School teacher'),'existing teacher identity, attributed once');
 assert.equal((ct1.match(/Your Kiddo School teacher/g)||[]).length,1,'teacher attribution not repeated');
 assert.ok(ct1.includes('href="/my-classroom/"'),'Back to My Classroom');
 assert.ok(ct1.includes('href="/learning-path/"'),'Learning Path');
 assert.ok(ct1.includes('href="/toddler/2-years/"'),'Age 2');
 assert.equal((ct1.match(/guide, not a test/g)||[]).length,1,'age-guide line appears exactly once');
 assert.ok(!/\b(scores?|failed|quiz|quizzes|percent|stars?|badges?|streaks?|leaderboards?|grades?)\b/i.test(ct1.replace(/<img class="doodle[^>]*>/g,''))&&!ct1.includes('Wrong!'),'no scores, grades, quizzes or gamification (doodle mascot asset names excluded)');
 assert.ok(!/camera|microphone|audio|autoplay/.test(ct1),'no camera, microphone or fake audio');
 assert.ok(!/timer|countdown/.test(ct1),'no timer or pressure');
 assert.ok(!/must|should already|needs to be able to/.test(ct1),'no developmental pressure language');
 assert.ok(!/gross motor|fine motor|developmental benefit|educational benefit/i.test(ct1),'no developmental lectures');
 assert.match(ct1,/BreadcrumbList[\s\S]*"name":"Toddler"[\s\S]*"name":"Age 2"[\s\S]*"name":"Circle Time"[\s\S]*"name":"Hello School!"/);
 assert.ok(ct1.includes('"learningResourceType":"Interactive circle time"'));
});
test('the circle time index page lists circle time 1 and nothing invented',()=>{
 assert.ok(cthub.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/circle-time/"'));
 assert.ok(cthub.includes('<h1>Circle Time</h1>'));
 assert.ok(cthub.includes('href="/toddler/2-years/circle-time/hello-school/"'));
 assert.ok(cthub.includes('href="/my-classroom/"'));
 assert.ok(cthub.includes('href="/learning-path/"'));
 assert.ok(!cthub.includes('Circle Time 2'),'no invented circle time 2');
});
test('my classroom connects the rug to circle time and every hotspot to a real page',()=>{
 assert.ok(mc.includes('rel="canonical" href="https://kiddo-school.pages.dev/my-classroom/"'));
 assert.ok(mc.includes('<h1>My Classroom</h1>'));
 assert.ok(mc.includes('src="https://pub-f2fcb7c9b45a496cbeefef18dbba0ec0.r2.dev/school/my-classroom/my-classroom-age-2.webp" width="1366" height="768"'));
 for(const [label,href] of [['Today’s class','/learning-path/'],['Our Classroom','/toddler/2-years/our-classroom/'],['Sticky Notes','/sticky-note-wall/'],['Library','/learning-library/'],['Principal','/principals-office/'],['Calendar','/school-calendar/'],['Play &amp; Practice','/toddler/2-years/play-and-practice/'],['Let’s explore','/toddler/2-years/lets-explore/'],['My Work','/toddler/2-years/my-work/'],['My School Bag','/my-school-bag/'],['Circle Time','#circle-time']])assert.ok(mc.includes('href="'+href+'"')&&mc.includes('>'+label+'</a>'),label);
 assert.ok(mc.includes('mc-hot-desk')&&mc.includes('mc-hot-shelf')&&mc.includes('mc-hot-bag')&&mc.includes('mc-hot-rules')&&mc.includes('mc-hot-wall')&&mc.includes('mc-hot-calendar'),'desk, shelf, bag, rules poster, wall and calendar hotspots exist');
 assert.ok(mc.includes('id="circle-time"'),'the rug panel exists');
 assert.ok(mc.includes('<h2>Hello School!</h2>'),'rug panel says Hello School!');
 assert.ok(mc.includes('href="/toddler/2-years/circle-time/hello-school/"')&&mc.includes('Start Circle Time'),'clear Start Circle Time action');
 assert.ok(mc.includes('/assets/circle-time.js'),'runner script loads on my classroom');
 assert.ok(mc.includes('aria-label="Places in the classroom"'));
});
test('lesson 9 links forward to lesson 10, lesson 10 to lesson 11, lesson 11 to lesson 12, lesson 12 to lesson 13, and each links back',()=>{
 assert.ok(l9.includes('href="/toddler/2-years/matching-and-sorting/"'));
 assert.ok(l9.includes('Next class'));
 assert.ok(l10.includes('href="/toddler/2-years/animals-and-sounds/"'));
 assert.ok(l10.includes('Next class'));
 assert.ok(l11.includes('href="/toddler/2-years/vehicles-and-sounds/"'),'lesson 11 links to lesson 12');
 assert.ok(l11.includes('Next class'));
 assert.ok(l12.includes('href="/toddler/2-years/emotions-and-feelings/"'),'lesson 12 links to lesson 13');
 assert.ok(l12.includes('Next class'));
 assert.ok(l12.includes('href="/toddler/2-years/animals-and-sounds/"'),'lesson 12 links back to lesson 11');
 assert.ok(l13.includes('href="/toddler/2-years/vehicles-and-sounds/"'),'lesson 13 links back to lesson 12');
});
test('stage pages exist, follow the school hierarchy and link their lessons',()=>{
 const w=read('dist/newborn/6-12-weeks/index.html');
 assert.ok(w.includes('rel="canonical" href="https://kiddo-school.pages.dev/newborn/6-12-weeks/"'));
 assert.ok(w.includes('NEWBORN 2'));
 assert.ok(w.includes('href="/newborn/6-12-weeks/faces-and-visual-tracking/"'));
 assert.ok(w.includes('Visual tracking, faces, sound'));
 const m=read('dist/baby/3-4-months/index.html');
 assert.ok(m.includes('rel="canonical" href="https://kiddo-school.pages.dev/baby/3-4-months/"'));
 assert.ok(m.includes('INFANT 1'));
 assert.ok(m.includes('href="/baby/3-4-months/colors-and-first-objects/"'));
 assert.ok(m.includes('Vision, movement, communication'));
 const i2=read('dist/baby/4-6-months/index.html');
 assert.ok(i2.includes('rel="canonical" href="https://kiddo-school.pages.dev/baby/4-6-months/"'));
 assert.ok(i2.includes('INFANT 2'));
 assert.ok(i2.includes('href="/baby/4-6-months/first-words-familiar-things/"'));
 assert.ok(i2.includes('Talk, first words, listening'));
 const e1=read('dist/baby/6-9-months/index.html');
 assert.ok(e1.includes('rel="canonical" href="https://kiddo-school.pages.dev/baby/6-9-months/"'));
 assert.ok(e1.includes('EXPLORER 1'));
 assert.ok(e1.includes('href="/baby/6-9-months/animals-everyday-objects/"'));
 assert.ok(e1.includes('Talk, thinking, recognition'));
 const e2=read('dist/baby/9-12-months/index.html');
 assert.ok(e2.includes('rel="canonical" href="https://kiddo-school.pages.dev/baby/9-12-months/"'));
 assert.ok(e2.includes('EXPLORER 2'));
 assert.ok(e2.includes('href="/baby/9-12-months/first-actions-body-parts/"'));
 assert.ok(e2.includes('Talk, thinking, movement'));
 const talk=read('dist/subjects/talk/index.html');
 assert.ok(talk.includes('rel="canonical" href="https://kiddo-school.pages.dev/subjects/talk/"'));
 assert.ok(talk.includes('href="/baby/4-6-months/first-words-familiar-things/"'));
 const tt=read('dist/subjects/talk-and-think/index.html');
 assert.ok(tt.includes('rel="canonical" href="https://kiddo-school.pages.dev/subjects/talk-and-think/"'));
 assert.ok(tt.includes('href="/baby/6-9-months/animals-everyday-objects/"'));
 const t1=read('dist/toddler/12-18-months/index.html');
 assert.ok(t1.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/12-18-months/"'));
 assert.ok(t1.includes('TODDLER 1'));
 assert.ok(t1.includes('href="/toddler/12-18-months/first-words-food-home/"'));
 const t2=read('dist/toddler/18-24-months/index.html');
 assert.ok(t2.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/18-24-months/"'));
 assert.ok(t2.includes('TODDLER 2'));
 assert.ok(t2.includes('href="/toddler/18-24-months/first-concepts-big-small-up-down/"'));
 const t3=read('dist/toddler/2-years/index.html');
 assert.ok(t3.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/2-years/"'));
 assert.ok(t3.includes('TODDLER 3'));
 assert.ok(t3.includes('href="/toddler/2-years/colors-and-shapes/"'));
 assert.ok(t3.includes('href="/toddler/2-years/matching-and-sorting/"'));
 assert.ok(t3.includes('href="/toddler/2-years/animals-and-sounds/"'));
 assert.ok(t3.includes('href="/toddler/2-years/vehicles-and-sounds/"'));
 assert.ok(t3.includes('href="/toddler/2-years/emotions-and-feelings/"'));
 assert.ok(t3.includes('href="/toddler/2-years/circle-time/hello-school/"'),'age-2 hub links circle time');
 assert.ok(t3.includes('href="/my-classroom/"'),'age-2 hub links my classroom');
 assert.ok(t3.includes('Colors, shapes, matching'));
 assert.ok(t3.includes('Toddler 3, 4, 5, 6, 7 &amp; 8'));
 assert.ok(t3.includes('href="/toddler/2-years/garden-bugs-and-friends/"'),'age-2 hub links lesson 14');
 const toddler=read('dist/toddler/index.html');
 assert.ok(toddler.includes('rel="canonical" href="https://kiddo-school.pages.dev/toddler/"'));
 assert.ok(toddler.includes('href="/toddler/12-18-months/first-words-food-home/"'));
 assert.ok(toddler.includes('href="/toddler/18-24-months/first-concepts-big-small-up-down/"'));
 assert.ok(toddler.includes('href="/toddler/2-years/colors-and-shapes/"'));
 assert.ok(toddler.includes('href="/toddler/2-years/matching-and-sorting/"'));
 assert.ok(toddler.includes('href="/toddler/2-years/animals-and-sounds/"'));
 assert.ok(toddler.includes('href="/toddler/2-years/vehicles-and-sounds/"'));
 assert.ok(toddler.includes('href="/toddler/2-years/emotions-and-feelings/"'));
 assert.ok(toddler.includes('href="/toddler/2-years/garden-bugs-and-friends/"'),'toddler hub links lesson 14');
 assert.ok(toddler.includes('href="/toddler/2-years/circle-time/hello-school/"'),'toddler hub links circle time');
});
test('the learning path page lists the real curriculum from birth to age 2 and beyond',()=>{
 const lp=read('dist/learning-path/index.html');
 assert.ok(lp.includes('rel="canonical" href="https://kiddo-school.pages.dev/learning-path/"'));
 assert.ok(lp.includes('Age ranges are a guide, not a test'));
 for(const s of [['Newborn 1','/newborn/0-6-weeks/high-contrast-cards/'],['Newborn 2','/newborn/6-12-weeks/faces-and-visual-tracking/'],['Infant 1','/baby/3-4-months/colors-and-first-objects/'],['Infant 2','/baby/4-6-months/first-words-familiar-things/'],['Explorer 1','/baby/6-9-months/animals-everyday-objects/'],['Explorer 2','/baby/9-12-months/first-actions-body-parts/'],['Toddler 1','/toddler/12-18-months/first-words-food-home/'],['Toddler 2','/toddler/18-24-months/first-concepts-big-small-up-down/'],['Toddler 3','/toddler/2-years/colors-and-shapes/'],['Toddler 4','/toddler/2-years/matching-and-sorting/'],['Toddler 5','/toddler/2-years/animals-and-sounds/'],['Toddler 6','/toddler/2-years/vehicles-and-sounds/'],['Toddler 7','/toddler/2-years/emotions-and-feelings/'],['Toddler 8','/toddler/2-years/garden-bugs-and-friends/']])assert.ok(lp.includes('>'+s[0])&&lp.includes('href="'+s[1]+'"'),s[0]);
 for(const hub of ['/newborn/6-12-weeks/','/baby/3-4-months/','/baby/4-6-months/','/baby/6-9-months/','/baby/9-12-months/','/toddler/12-18-months/','/toddler/18-24-months/','/toddler/2-years/'])assert.ok(lp.includes('href="'+hub+'"'),hub);
 assert.ok(lp.includes('href="/art/"')&&lp.includes('href="/activities/"'));
 assert.ok(lp.includes('Start Today’s Class'));
});
test('the school homepage: short hero, age chooser, real classes, how school works',()=>{
 const home=read('dist/index.html');
 assert.ok(home.includes('<h1>Their first school<br><em>starts with you.</em></h1>'));
 assert.ok(home.includes('A playful digital school from birth onward. Explore age-guided classes, hands-on activities, and simple ways to learn together at home.'),'single approved hero paragraph');
 assert.ok(!home.includes('hero-footnote'),'tiny text below the buttons is gone');
 assert.ok(!home.includes('promise-strip'),'the strip under the hero is gone');
 assert.ok(home.includes('href="/newborn/0-6-weeks/high-contrast-cards/"'));
 assert.equal((home.match(/Start Today’s Class/g)||[]).length>=3,true);
 assert.ok(home.includes('href="/learning-path/"'));
 assert.ok(home.includes('newborn-high-contrast-face.webp'));
 assert.ok(home.includes('CHOOSE YOUR CHILD’S AGE'),'age chooser directly below the hero');
 assert.ok(home.includes('id="choose-age"'));
 assert.ok(home.includes('href="/newborn/"')&&home.includes('href="/baby/"')&&home.includes('href="/toddler/"')&&home.includes('href="/preschool/3-years/"'),'four real stage cards');
 assert.ok(home.includes('EXPLORE REAL CLASSES'),'real-classes section');
 assert.ok(home.includes('Twenty-nine classes are ready now, from birth to age five'),'honest class count');
 assert.ok(home.includes('HOW OUR SCHOOL WORKS'));
 assert.ok(home.includes('id="how-school-works"'));
 for(const step of ['Learn','Play','Practice','Off-Screen'])assert.ok(new RegExp('<h3>'+step+'</h3>').test(home),'step '+step);
 assert.ok(!home.includes('<h3>Explore</h3>'),'old five-step notebook replaced');
 assert.ok(home.includes('FROM THE PRINCIPAL’S OFFICE'));
 assert.ok(home.includes('href="/about/#principal"'));
 assert.ok(home.includes('href="/grown-ups/"'));
 assert.ok(home.includes('OUR LITTLE CLASSROOMS'));
 assert.ok(home.includes('href="/art/"'));
 assert.ok(home.includes('href="/activities/"'));
 assert.ok(!home.includes('id="ages"'),'the older-kid activity ages panel no longer competes on the homepage');
 assert.ok(!home.includes('FROM THE ACTIVITY WALL'),'the activity strip no longer competes on the homepage');
 assert.ok(!home.includes('A QUESTION WORTH TRYING'),'the bridge feature no longer competes on the homepage');
 assert.ok(home.includes('data-tc-today'),'Today’s Class buttons are smart (age + progress aware)');
 assert.ok(home.includes('data-tc-hint'),'the recommendation hint travels with the buttons');
 assert.ok(read('dist/ages/index.html').includes('id="ages"')||read('dist/ages/index.html').includes('age-panel'),'the /ages/ page still exists for older-kid activities');
 const about=read('dist/about/index.html');
 assert.ok(about.includes('id="principal"'));
 assert.ok(about.includes('From the Principal’s Office'));
 assert.ok(about.includes('href="/learning-path/"'));
 assert.ok(about.includes('Twenty-nine classes from birth to age five are ready today'),'about count updated');
});
test('the whole curriculum path is wired together and reusable markup is shared',()=>{
 const l1=read('dist/newborn/0-6-weeks/high-contrast-cards/index.html');
 assert.ok(l1.includes('href="/newborn/6-12-weeks/faces-and-visual-tracking/"'));
 const hub=read('dist/newborn/index.html');
 assert.ok(hub.includes('href="/newborn/6-12-weeks/faces-and-visual-tracking/"'));
 const baby=read('dist/baby/index.html');
 assert.ok(baby.includes('href="/baby/3-4-months/"'));
 assert.ok(baby.includes('href="/baby/4-6-months/"'));
 assert.ok(baby.includes('href="/baby/6-9-months/"'));
 assert.ok(baby.includes('href="/baby/9-12-months/"'));
 assert.ok(baby.includes('href="/toddler/12-18-months/"'));
 assert.ok(baby.includes('href="/newborn/6-12-weeks/"'));
 const see=read('dist/subjects/see/index.html');
 for(const L of [lessons[0],lessons[1],lessons[2]])assert.ok(see.includes('href="'+L.path+'"'));
 const talkHub=read('dist/subjects/talk/index.html');
 assert.ok(talkHub.includes('href="'+fwftLesson.path+'"'));
 assert.ok(talkHub.includes('href="'+aeoLesson.path+'"'));
 assert.ok(talkHub.includes('href="'+fabLesson.path+'"'));
 assert.ok(talkHub.includes('href="'+fwfhLesson.path+'"'));
 const talkThinkHub=read('dist/subjects/talk-and-think/index.html');
 assert.ok(talkThinkHub.includes('href="'+aeoLesson.path+'"'));
 assert.ok(talkThinkHub.includes('href="'+fabLesson.path+'"'));
 assert.ok(talkThinkHub.includes('href="'+fwfhLesson.path+'"'));
 assert.ok(talkThinkHub.includes('href="'+fcLesson.path+'"'));
 assert.ok(talkThinkHub.includes('href="'+msLesson.path+'"'));
 for(const html of [l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13]){
  assert.ok(html.includes('class="lv-frame" data-lesson-viewer'));
  assert.ok(html.includes('<div class="lv-stage" data-lv-stage></div>'));
 }
});

test("today's class: one curriculum source, smart buttons, real progress machinery",()=>{
 const home=read('dist/index.html');
 const classroom=read('dist/my-classroom/index.html');
 const curriculum=read('dist/assets/curriculum.js');
 const engine=read('dist/assets/school-progress.js');
 // the curriculum ships to the client straight from the single source
 assert.ok(curriculum.includes('window.KIDDO_CURRICULUM'));
 const list=JSON.parse(curriculum.slice(curriculum.indexOf('['),curriculum.lastIndexOf(']')+1));
 assert.equal(list.length,29,'exactly 29 classes in the shipped curriculum (23 and 24 stay reserved);');
 assert.equal(list.filter(c=>c.band==='age3').length,8,'eight Age 3 classes');
 assert.equal(list[0].path,'/newborn/0-6-weeks/high-contrast-cards/','class 1 is the newborn class');
 // smart today's-class links on nav + homepage, with the Learning Path fallback
 assert.ok((home.match(/data-tc-today/g)||[]).length>=3,'three smart CTAs on the homepage');
 assert.ok(home.includes('data-tc-today${')===false);
 assert.ok(classroom.includes('data-tc-today'),'nav link is smart on My Classroom too');
 // homepage CTAs keep the honest class-1 fallback for no-JS guests
 assert.ok(home.includes('href="/newborn/0-6-weeks/high-contrast-cards/" data-tc-today'));
 // the desk exists and the engine knows how to fill it
 assert.ok(classroom.includes('data-tc-desk'),'My Classroom has the child desk mount');
 assert.ok(classroom.includes('curriculum.js')&&classroom.includes('school-progress.js'),'My Classroom loads the progress scripts');
 for(const marker of ['recommendFor','kiddo-children','kiddo-progress','data-tc-desk','data-tc-mark','localStorage']){
  assert.ok(engine.includes(marker),'progress engine has '+marker);
 }
 // privacy: nothing personal leaves the device; the engine never posts anywhere
 assert.ok(!engine.includes('fetch('),'progress engine never talks to the network');
 assert.ok(engine.includes('no account')||engine.includes('No account'),'honest privacy note in the engine copy');
 // the class pages carry the engine so visits + completion are recorded
 for(const p of ['/preschool/3-years/shapes-and-patterns/','/newborn/0-6-weeks/high-contrast-cards/']){
  const html=read('dist'+p+'index.html');
  assert.ok(html.includes('/assets/school-progress.js'),'engine loads on '+p);
  assert.ok(html.includes('/assets/curriculum.js'),'curriculum loads on '+p);
 }
 assert.ok(read('dist/preschool/3-years/shapes-and-patterns/index.html').includes('id="class-complete"'),'preschool classes have the completion anchor');
 assert.ok(engine.includes("querySelector('#class-complete')")&&engine.includes("getElementById('main')"),'completion bar lands on every class page shape');
 // guest age picker copy is honest about device-only storage
 assert.ok(engine.includes('no sign-up'));
});
