// Kiddo School — the Alphabet Learning Center data: all 26 letters, their
// R2 artwork (school/alphabet/<letter>/ on the site's public bucket), honest
// phonics and per-letter teaching copy. Every picture fact below was written
// from the actual artwork after visual inspection of all 26 picture cards.
//
// Asset notes from the probe of all 156 files:
//  - letters a, b and c keep their uploaded object.png (the legacy name the
//    brief warns about); every other letter uses picture.png. The pictureFile
//    field records the real path — nothing is renamed or re-uploaded.
//  - letter a ships at its true square 1080×1080; the other 25 letters are
//    1080×1350 portrait. True dimensions ship everywhere.
//  - the uploaded tracing.png sheets are deliberately NOT used: the brief
//    flags their numbering as incorrect, so the tracing sections use the
//    site's own verified SVG letterforms instead (src/tracing-strokes.mjs).
export const R2_ALPHA='https://pub-f2fcb7c9b45a496cbeefef18dbba0ec0.r2.dev/school/alphabet/';

/* phonics.kind values (used by the beginning-sounds game and the tests):
   'plain'  — the pictured word really begins with the letter's most common sound
   'soft'   — a deliberate two-sound letter taught by its pictured word (g)
   'long'   — the pictured word uses the letter's name sound (i)
   'special'— x: taught as letter recognition + end-of-word /ks/           */
const L=(letter,word,pictureFile,w,h,pictureAlt,phonics,copy)=>({
 letter,word,lower:letter,upper:letter.toUpperCase(),
 pictureFile,w,h,pictureAlt,
 ...phonics,...copy,full:R2_ALPHA+letter+'/',file:n=>R2_ALPHA+letter+'/'+n
});

export const LETTERS=[
 L('a','Apple','object.png',1080,1080,
  'A red apple with a green leaf and a brown stem',
  {kind:'plain',soundSay:'a — aaa, like the very start of apple',beginningDistractors:['m','t'],
   soundCopy:'The letter is named A, but in apple you hear its sound: aaa — the first sound out of your mouth. A is a vowel with more than one sound; this short a is the friendliest one to start with.'},
  {intro:'Big A, little a and a shiny red apple — the friendliest place to start the alphabet, because snack time has already done half of the teaching.',
   upperCopy:'A looks like a mountain with a bridge across the middle: two slides down and one straight line across. Point it out on signs and book covers — it is everywhere.',
   lowerCopy:'Little a sits inside the line like a round bowl with a short wall on the right. It is the same letter as big A, just smaller and rounder.',
   pairCopy:'Big A and little a are the same letter in two sizes. Once your child can spot both, the alphabet has officially started.',
   activity:{title:'Apple taste test',steps:['Cut three fruits into slices — an apple and two others.','Say aaa each time your child tastes the apple: aaa, apple!','Ask which of the three fruits starts with aaa, and let your child be the judge.']}},),
 L('b','Ball','object.png',1080,1350,
  'A blue beach ball with white curved stripes',
  {kind:'plain',soundSay:'b — buh, a quick lip pop',beginningDistractors:['a','n'],
   soundCopy:'B makes a quick lip pop: buh, like the start of ball and bubble. Press your lips together, pop them open and there it is.'},
  {intro:'A bouncy blue ball for a bouncy letter. B starts ball, bath, bubbles and half the fun of the day — this card gives all of that a friendly face.',
   upperCopy:'Big B has a straight back and two round bumps, like a little train with two carriages. Count the bumps together — one, two!',
   lowerCopy:'Little b is a tall stick with one round belly on the right. The belly always faces the same way — a friendly reminder when b and d get mixed up.',
   pairCopy:'Big B and little b share one shape trick: the bumps always open to the right. Same letter, two sizes, one belly.',
   activity:{title:'Ball bounce beat',steps:['Bounce a ball back and forth in the garden or hallway.','Say buh with every bounce — the sound lands on the floor and sticks.','Finish with: B is for ball! Then let your child throw it to you.']}},),
 L('c','Cat','object.png',1080,1350,
  'A green cat sitting with its tail curled around its paws',
  {kind:'plain',soundSay:'c — kuh, like cat',beginningDistractors:['b','u'],
   soundCopy:'In cat, the letter c says kuh — the same sound k makes. C is a letter of many talents (it can borrow the s sound in words like circle), but cat keeps it simple.'},
  {intro:'A quiet green cat for the letter C. Cats are household celebrities for small children — real ones, neighbour’s ones and the one in every second picture book.',
   upperCopy:'Big C is one open curve, like a half-open mouth or the rim of a cup. One stroke, no lift — a lovely first letter to trace in the air.',
   lowerCopy:'Little c is the same open curve, tucked between the lines. Draw it in the air, on your child’s back, in a plate of yogurt — curves love surfaces.',
   pairCopy:'Big C and little c are both one open curve — the little one simply sits lower. Say kuh together, then creep around the room like cats.',
   activity:{title:'Cat creep',steps:['Creep around the room on hands and knees, whispering kuh, kuh, cat!','Freeze when you reach a chair, then prowl on.','End curled up in a cat nap together — two breaths is plenty.']}},),
 L('d','Dog','picture.png',1080,1350,
  'An orange dog sitting with its tail up',
  {kind:'plain',soundSay:'d — duh, like dog',beginningDistractors:['l','p'],
   soundCopy:'D says duh, a quick tongue tap behind the teeth, like the start of dog. Say it fast — duh — and never duh-uh; the short version is the one that helps with reading.'},
  {intro:'A happy orange dog with its tail up, for the letter D. If your family has a dog, this card will be requested every single day.',
   upperCopy:'Big D is a tall straight line with a big round belly on the right, like a half moon leaning on a wall.',
   lowerCopy:'Little d is a circle with a tall stick on the right — the opposite of little b, which wears its stick on the left. The stick side is the whole secret.',
   pairCopy:'Big D and little d both keep the round part on the left and the tall part on the right. Say duh like a dog panting: d, d, d!',
   activity:{title:'Dog tricks',steps:['Pretend to be dogs together: pant d, d, d.','Teach your dog a trick — roll over, sit, stay — saying duh with each command.','Finish with a big dog shake and a laugh.']}},),
 L('e','Elephant','picture.png',1080,1350,
  'The letters E e beside a purple elephant',
  {kind:'plain',soundSay:'e — eh, like elephant',beginningDistractors:['d','m'],
   soundCopy:'E says eh, like the start of elephant — a short, open sound. E is the busiest letter in the alphabet, and this short eh is the sound to meet first.'},
  {intro:'The letter E arrives with a purple elephant already beside it — big E, little e and one of the biggest, gentlest animals your child can name.',
   upperCopy:'Big E is a straight spine with three shelves: top, middle and bottom. Four strokes, three shelves — count them together.',
   lowerCopy:'Little e is one smooth curve with a shelf across the middle. It is written without lifting — a tiny rollercoaster that starts in the middle.',
   pairCopy:'Big E stands tall with three shelves; little e curls between the lines. Same letter, same eh sound, two very different shapes — that is worth a giggle.',
   activity:{title:'Elephant walk',steps:['Swing one arm in front of your nose like a trunk and stomp around: eh, eh, elephant!','Pick up three toys with your trunk and put them in a basket.','Curl up small like a sleeping elephant when the walk is done.']}},),
 L('f','Fish','picture.png',1080,1350,
  'The letters F f beside a teal fish',
  {kind:'plain',soundSay:'f — fff, a long windy sound',beginningDistractors:['m','d'],
   soundCopy:'F says fff — a long, windy sound made with top teeth on the bottom lip. Hold it out: fffff. If it tickles your lip, you are doing it right.'},
  {intro:'The letters F f swim in with a teal fish. F is a windy, whispery letter — you can feel it on your lip, which makes it irresistible to children.',
   upperCopy:'Big F is a straight spine with a long top shelf and a short middle shelf — like E without its bottom shelf. Spot the missing shelf together.',
   lowerCopy:'Little f is a tall stroke with a graceful hook at the top and a crossbar through the middle — the only letter that wears its bar like a scarf.',
   pairCopy:'Big F stands straight; little f curls its top. Both say fff. Blow a feather or a tissue across the table and say fffff as it flies.',
   activity:{title:'Wind and fish',steps:['Cup your hands like a fish and swim them through the air while saying fff.','Blow a tissue up in the air with a long fffff and catch it.','Finish with five fast fish kisses — pop your lips like a fish five times.']}},),
 L('g','Giraffe','picture.png',1080,1350,
  'The letters G g beside a yellow giraffe',
  {kind:'soft',soundSay:'g — in giraffe it says j',beginningDistractors:['b','z'],
   soundCopy:'G has two sounds, and our giraffe teaches the tricky one: in giraffe, g says j. In goat, game and go it says the harder g. Both are right — giraffe simply picked the j sound.'},
  {intro:'The letters G g arrive beside a yellow giraffe — the letter with two voices, and the animal that proves the alphabet is full of surprises.',
   upperCopy:'Big G is a round curve with a little shelf tucked inside at the bottom right — C with a secret pocket.',
   lowerCopy:'Little g is a round bowl with a tail that swings below the line, curling to the left like a fishhook.',
   pairCopy:'Big G and little g both keep that tucked-in shelf or hook. Say j, j, giraffe together — then gallop around the room with long giraffe steps.',
   activity:{title:'Giraffe stretch',steps:['Reach up high like a giraffe reaching leaves: j, j, giraffe!','Munch imaginary leaves with slow, chewing bites.','Walk with long stiff legs back to the sofa and rest your long neck.']}},),
 L('h','House','picture.png',1080,1350,
  'A blue house with a chimney and an open doorway',
  {kind:'plain',soundSay:'h — hhh, a soft breath',beginningDistractors:['b','m'],
   soundCopy:'H says hhh — just a breath, like warming your hands or giggling quietly. Hold your palm in front of your mouth: if you feel air, the sound is there.'},
  {intro:'A sturdy blue house with a chimney, for the letter H. H is a breath of a letter — you cannot see it, but you can feel it on your hand.',
   upperCopy:'Big H is two tall lines holding hands across the middle. Two strokes down, one bridge across — build it like a doorframe.',
   lowerCopy:'Little h is a tall line with an arch that walks away to the right — a little like a chair back, or a door half open.',
   pairCopy:'Big H and little h both start with the same tall line. Breathe on your hand and say hhh — house, hat, home.',
   activity:{title:'House hunt',steps:['Walk through your home finding things that start with hhh: house, hat, hand, hair.','Knock on three doors in your home and say hhh, hello!','Draw your house together and put a big H on the door.']}},),
 L('i','Ice Cream','picture.png',1080,1350,
  'A red ice cream cone with a swirl of ice cream',
  {kind:'long',soundSay:'i — ie, ice cream starts with I’s name sound',beginningDistractors:['d','z'],
   soundCopy:'Ice cream starts with I’s name sound: ie. The little i also has a short ih sound, as in insect — for now, meet the long ie of ice, the one your child already says when they shout ice cream!'},
  {intro:'The letter I melts in with an ice cream cone. I is the only letter that introduces itself by name here — ice starts with ie, just like the letter’s own name.',
   upperCopy:'Big I is a straight line with a bar on top and a bar below — like a little letter sandwich. The bars stop I from getting lost next to numbers.',
   lowerCopy:'Little i is a short stick with one dot floating above — the only lowercase letter with its own little hat.',
   pairCopy:'Big I wears two bars; little i wears one dot. Say ie, ie, ice cream — then draw a giant pretend ice cream together and choose the flavors.',
   activity:{title:'Ice cream shop',steps:['Open an ice cream shop with paper scoops and a wooden spoon for a scoop.','Every order starts with ie, ie, ice cream!','Pay for each cone with a hug — the shop accepts nothing else.']}},),
 L('j','Jellyfish','picture.png',1080,1350,
  'A purple jellyfish with long wavy arms',
  {kind:'plain',soundSay:'j — juh, like jellyfish',beginningDistractors:['a','t'],
   soundCopy:'J says juh, like the start of jellyfish and jump. Say it quickly — juh — and then jump! The movement teaches the sound better than any flashcard.'},
  {intro:'A purple jellyfish with long wavy arms floats in for the letter J. J is a jumping, jiggly letter, and the jellyfish is the perfect mascot.',
   upperCopy:'Big J is a straight line with a hook that curls to the left at the bottom, like a fishing rod pulling in a catch.',
   lowerCopy:'Little j is a short stick with a tail below the line, curled left, plus its famous dot floating on top.',
   pairCopy:'Big J and little j both hook to the left at the bottom, and little j adds the dot. Say juh, then jump three times — j is for jump too.',
   activity:{title:'Jellyfish float',steps:['Let your arms dangle like jellyfish arms and wobble around the room: juh, juh, jellyfish.','Play a freeze game — when the music stops (or you stop humming), freeze like a still jellyfish.','Finish with three small jumps: juh, juh, jump!']}},),
 L('k','Kite','picture.png',1080,1350,
  'An orange kite with bows on its tail',
  {kind:'plain',soundSay:'k — kuh, a clean click',beginningDistractors:['b','m'],
   soundCopy:'K says kuh — a clean little click at the back of the mouth, exactly like c in cat. Two letters, one sound: that is a fun secret to tell your child.'},
  {intro:'An orange kite with ribbon bows flies in for the letter K. K clicks like a tiny lock, and the kite gives the click somewhere wonderful to go.',
   upperCopy:'Big K is a tall line with one leg kicking in and another kicking out — like a person mid-stride.',
   lowerCopy:'Little k keeps the same kick: a tall line, one slide in to the middle, one slide out to the bottom.',
   pairCopy:'Big K and little k both stride — in, then out. Say kuh and flap your arms like a kite dipping in the wind.',
   activity:{title:'Kite run',steps:['Run around the garden or room holding a ribbon or scarf behind you like a kite tail.','Say kuh, kuh, kite with every lap.','Crash-land on a cushion at the end, laughing.']}},),
 L('l','Leaf','picture.png',1080,1350,
  'A teal leaf with white veins',
  {kind:'plain',soundSay:'l — lll, a tall singing sound',beginningDistractors:['d','p'],
   soundCopy:'L says lll — made with the tongue tip up behind the teeth, a tall singing sound. Hold it out: llll. If your tongue tickles, that is the spot.'},
  {intro:'A teal leaf drifts in for the letter L. L is a tall, calm letter — one straight line down, then a small slide to the right, like standing up and taking a step.',
   upperCopy:'Big L is a tall line with a short foot: pull down, slide right, no lift. Two motions, one stroke — a favorite first letter to write.',
   lowerCopy:'Little l is just one tall stick — the simplest letter in the whole alphabet, and very proud of it.',
   pairCopy:'Big L has a foot; little l is only a stick. Say lll slowly like a gentle siren, then find leaves, laps and lips around the house.',
   activity:{title:'Leaf collecting',steps:['Collect three leaves outside (or paper cut-outs) and hold each up: lll, leaf.','Race the leaves: drop two and blow them across the table saying llll.','Press the favorite leaf under a heavy book to keep.']}},),
 L('m','Moon','picture.png',1080,1350,
  'A green crescent moon',
  {kind:'plain',soundSay:'m — mmm, a humming sound',beginningDistractors:['d','k'],
   soundCopy:'M says mmm — the only sound you can hum with your mouth closed. Say mmmm while patting your tummy like you just ate something wonderful.'},
  {intro:'A green crescent moon glows for the letter M. M is the humming letter — mmm — and the moon is the quietest, coziest word in the set.',
   upperCopy:'Big M is four lines: down the hill, up the mountain, down again. Like drawing two mountain peaks with a pencil that never lifts.',
   lowerCopy:'Little m is a short stick with two arches, like two little doors. Three strokes: down, arch, arch.',
   pairCopy:'Big M climbs mountains; little m makes two arches. Hum mmm together — then whisper it, then hum it loud like a moon monster.',
   activity:{title:'Moon light',steps:['Turn off the lamp for one minute and pretend to be moonlight drifting around the room, humming mmmm.','Find three white or round things in the dark and name them.','Turn the light back on with a big mmm-ON!']}},),
 L('n','Nest','picture.png',1080,1350,
  'A red nest woven from twigs',
  {kind:'plain',soundSay:'n — nnn, a nose sound',beginningDistractors:['d','m'],
   soundCopy:'N says nnn — made right in the nose, which is why it tickles. Say nnn and feel your nose vibrate. N is nnn and m is mmm: two neighbors, easy to feel apart.'},
  {intro:'A woven red nest sits for the letter N. A nest is a home a bird builds twig by twig — and n is the sound you feel right in your nose.',
   upperCopy:'Big N is down, down the hill, up. Three straight strokes: one tower, one slide, one tower again.',
   lowerCopy:'Little n is a short stick with one arch — half of little m. Down, arch, down.',
   pairCopy:'Big N zigzags; little n makes one arch. Say nnn like a tiny bee in your nose, then hunt for nest-like things: baskets, bowls, curled-up hands.',
   activity:{title:'Build a nest',steps:['Collect twigs, leaves or shredded paper and weave a tiny nest in a bowl.','Press a plastic egg or a round stone into the middle — tweet softly: nnn, nest.','Find a safe spot on a windowsill for your nest and admire it.']}},),
 L('o','Orange','picture.png',1080,1350,
  'An orange fruit with a green leaf',
  {kind:'plain',soundSay:'o — oh, a round open sound',beginningDistractors:['d','k'],
   soundCopy:'O says oh — a round, open sound you make with a big circle mouth. Like an orange! Say ohhh while opening your mouth wider and wider.'},
  {intro:'A round orange rolls in for the letter O. O is itself a perfect circle — and the orange is the roundest, friendliest word it could wear.',
   upperCopy:'Big O is one giant circle: start at the top right, sweep round anticlockwise and end where you began. No lift, no corners.',
   lowerCopy:'Little o is the same circle, small enough to sit between the lines. Round and round — the first letter many children learn to draw.',
   pairCopy:'Big O and little o are both just circles — one tall, one small. Say ohhh, then hunt for O shapes: rings, cup rims, round cereal.',
   activity:{title:'Orange roll',steps:['Roll an orange (or a ball) across the table to each other, saying ohhh with every roll.','Peel it together and breathe in the smell — that scent is the lesson sticking.','Share the segments and count them: oh, oh, oh — one, two, three.']}},),
 L('p','Penguin','picture.png',1080,1350,
  'A blue outline of a penguin with open wings',
  {kind:'plain',soundSay:'p — puh, a tiny pop',beginningDistractors:['d','m'],
   soundCopy:'P says puh — a tiny pop made with your lips, like a soap bubble bursting. Say puh into your child’s hand so they feel the little puff of air.'},
  {intro:'A waddling penguin arrives for the letter P. P pops like a small bubble — and penguins are the bounciest, most huggable pop in the animal kingdom.',
   upperCopy:'Big P is a tall line with one round belly at the top right — like a flag on a pole.',
   lowerCopy:'Little p is a stick that dives below the line, with its belly floating at the top. The only letter that goes swimming.',
   pairCopy:'Big P stands tall with its belly up top; little p dives below the line with the same belly. Say puh, then waddle like penguins with your heels together.',
   activity:{title:'Penguin waddle',steps:['Waddle around the room with a book (or a small cushion) balanced on your head: puh, puh, penguin.','Carry a pretend egg on your feet — three slow steps is a triumph.','Finish huddled together like a penguin family, flippers out.']}},),
 L('q','Quilt','picture.png',1080,1350,
  'A red quilt with a patchwork of squares and diamonds',
  {kind:'plain',soundSay:'q — kwuh, q brings u along',beginningDistractors:['b','m'],
   soundCopy:'Q almost never travels alone: q brings u along, and qu says kwuh — like the start of quilt and quick. Two letters, one team, one sound.'},
  {intro:'A red patchwork quilt tucks in for the letter Q. Q is a fancy circle with a little tail — and it always brings its best friend u to make kwuh.',
   upperCopy:'Big Q is a big circle with a small tail kicking out at the bottom right — O with a little flag.',
   lowerCopy:'Little q is a circle with a straight tail that dives below the line, standing proud next to the letter it always brings along.',
   pairCopy:'Big Q and little q both wear the tail. Say kwuh — quilt, quick, quiet — then wrap up in a real blanket and read one book together.',
   activity:{title:'Quilt hide-and-seek',steps:['Drape a blanket over two chairs to make a quilt tent.','Crawl under together and whisper kwuh words: quilt, quiet, quick.','Play one round of quick-peek: kwuh! — then read one short book inside.']}},),
 L('r','Rabbit','picture.png',1080,1350,
  'An orange outline of a rabbit sitting',
  {kind:'plain',soundSay:'r — rrr, a growling sound',beginningDistractors:['d','m'],
   soundCopy:'R says rrr — a growly sound made with a bouncy tongue. Pretend to be a tiger, then shrink it down: rrrabbit. The growl is the game.'},
  {intro:'An orange rabbit hops in for the letter R. R growls like a friendly tiger — rrr — and the rabbit gives the growl two long ears to listen with.',
   upperCopy:'Big R is a tall line, a small bump at the top and a leg kicking out to the right — a letter mid-jump.',
   lowerCopy:'Little r is a short stick with a tiny arm curving over to the right — the smallest bump in the alphabet.',
   pairCopy:'Big R has a leg for jumping; little r has a small arm. Say rrr like a soft growl, then hop three times like rabbits.',
   activity:{title:'Rabbit hop',steps:['Hop three times across the room, growling softly: rrr, rrr, rabbit!','Nibble an imaginary carrot with fast little bites.','Freeze like a still rabbit when you hear rrr — then hop to the sofa.']}},),
 L('s','Snake','picture.png',1080,1350,
  'The letters S s beside a green snake',
  {kind:'plain',soundSay:'s — sss, a hissing sound',beginningDistractors:['d','m'],
   soundCopy:'S says sss — a long hiss like a snake in the grass. Make it long and silly: sssss. If it sounds like air escaping a tire, it is perfect.'},
  {intro:'The letters S s slither in with a green snake. S hisses — sss — and is written as one wiggly stroke, just like a snake path.',
   upperCopy:'Big S is one swoopy stroke that curves one way, then the other — like a snake around a branch. No lift, no corners.',
   lowerCopy:'Little s is the same wiggle, small enough to sit between the lines. It is written in one move — and it wiggles.',
   pairCopy:'Big S and little s both slither. Say sss and walk your fingers across the table in a wiggly snake path.',
   activity:{title:'Snake trail',steps:['Walk your fingers in a wiggly line across the floor, hissing ssss.','Draw a giant S with chalk or on paper and walk a toy along the path.','Curl up like a coiled snake — one gentle squeeze — then uncoil with a hiss.']}},),
 L('t','Turtle','picture.png',1080,1350,
  'A blue outline of a turtle with a patterned shell',
  {kind:'plain',soundSay:'t — tuh, a quick tongue tap',beginningDistractors:['d','m'],
   soundCopy:'T says tuh — a quick tongue tap behind the top teeth, like a tiny clock: t, t, t. Keep it short and crisp — tuh, not tuh-uh.'},
  {intro:'A steady blue turtle walks in for the letter T. T ticks like a little clock — t, t, t — and the turtle is the most patient teacher of the sound.',
   upperCopy:'Big T is a tall line with a roof: pull down, then slide straight across the top. Down, then across.',
   lowerCopy:'Little t is a tall stick with a curve at the bottom and a crossbar through the middle — like little l wearing a belt.',
   pairCopy:'Big T wears a flat roof; little t wears a belt and curly shoes. Say t, t, t and stomp slowly like a turtle: one step per tick.',
   activity:{title:'Turtle pace',steps:['Walk the room at turtle speed — the slowest steps you can make — ticking t, t with each step.','Carry a cushion shell on your back for one lap.','Finish with a turtle stretch: arms and head tucked in, then out.']}},),
 L('u','Umbrella','picture.png',1080,1350,
  'An orange umbrella opened above its handle',
  {kind:'plain',soundSay:'u — uh, like umbrella',beginningDistractors:['d','k'],
   soundCopy:'U says uh, like the start of umbrella — a short, relaxed sound. When you are not sure what to say, you are already saying it: uh…'},
  {intro:'An open orange umbrella floats in for the letter U. U says uh — the sound you make when something surprises you, which rain usually does.',
   upperCopy:'Big U is a cup: slide down, curve round the bottom and climb back up the other side, then draw the second side straight down.',
   lowerCopy:'Little u is the same cup, small enough to sit between the lines: down, curve up, then a straight line down on the right.',
   pairCopy:'Big U and little u are both cups. Say uh, uh, umbrella — then open and close a real umbrella slowly together.',
   activity:{title:'Rainy day pretend',steps:['Open an umbrella indoors (over a towel) and stand under it: uh, umbrella!','Tap your fingers on the umbrella like rain drops, starting slow and getting faster.','Close it with a whoosh and listen for the big uh at the end.']}},),
 L('v','Violin','picture.png',1080,1350,
  'A purple violin with its bow',
  {kind:'plain',soundSay:'v — vvv, a motor sound',beginningDistractors:['d','m'],
   soundCopy:'V says vvv — like a little motor: top teeth on the bottom lip, voice switched on. Hold it out: vvvv. Compare with f, which is the same shape but only air.'},
  {intro:'A purple violin sings in for the letter V. V vibrates like a tiny motor — vvv — and the violin is the best motor in the orchestra.',
   upperCopy:'Big V is two slides: down to the point, then up. The point lands exactly on the line — aim for it.',
   lowerCopy:'Little v is the same two slides, small enough to sit between the lines. Down, up — two strokes.',
   pairCopy:'Big V and little v both come to a point. Say vvv and hold your palm to your cheek to feel the vibration — that buzz is the whole letter.',
   activity:{title:'Violin concert',steps:['Hold a ruler or paper tube as a violin and bow with your other arm while singing vvvv.','March once around the room playing for an audience of stuffed animals.','Finish with a deep bow — v is for very well done.']}},),
 L('w','Watermelon','picture.png',1080,1350,
  'A green watermelon with a striped rind',
  {kind:'plain',soundSay:'w — wuh, a windy round sound',beginningDistractors:['d','k'],
   soundCopy:'W says wuh — made with rounded lips blowing gently, like blowing out a candle without blowing it out. Say wuh and feel your lips make a small circle.'},
  {intro:'A striped watermelon rolls in for the letter W. W is the longest letter to say — double-u — and one zigzag stroke to write: down, up, down, up.',
   upperCopy:'Big W is four straight lines zigzagging: down, up, down, up. Two valleys and three peaks — count them as you trace.',
   lowerCopy:'Little w is the same zigzag between the lines. One stroke, no lift — down, up, down, up.',
   pairCopy:'Big W and little w both zigzag. Say wuh while making wind with your mouth, then hunt for wobbly W shapes in toys and laundry.',
   activity:{title:'Watermelon picnic',steps:['Spread a towel and have a watermelon picnic (real or pretend).','Knock on the watermelon with one knuckle — hear the wuh-wuh.','Eat a slice with tiny bites, saying wuh between each one.']}},),
 L('x','Xylophone','picture.png',1080,1350,
  'The letters X x beside a red xylophone with two mallets',
  {kind:'special',soundSay:'x — usually the ks at the end of fox and box',beginningDistractors:['m','d'],
   soundCopy:'X is a shape-shifter. In xylophone, the x actually starts with a z sound. Most of the time x says ks at the END of words: fox, box, six. Say fox slowly and hear the x hiding at the finish.'},
  {intro:'The letters X x arrive with a red xylophone. X is the alphabet’s shape-shifter: it rarely starts words, and when it does — as in xylophone — it secretly sounds like z.',
   upperCopy:'Big X is two slides that cross: down-right, then down-left. The two lines meet in the middle like a hug.',
   lowerCopy:'Little x is the same crossing hug between the lines. Two strokes, one cross — the only letter drawn as a hug.',
   pairCopy:'Big X and little x both cross in the middle. X’s sound usually hides at the end of words: fox, box, six. Tap the final sound of each word together.',
   activity:{title:'X marks the spot',steps:['Draw a treasure map of a room and mark the treasure with a big X.','Hunt for things whose names end with the ks sound: box, blocks, socks.','Tap the final sound together: fo-ks, bo-ks, si-ks — then open the treasure (a snack counts).']}},),
 L('y','Yo-yo','picture.png',1080,1350,
  'A blue yo-yo with its string looping down',
  {kind:'plain',soundSay:'y — yuh, like yo-yo',beginningDistractors:['a','m'],
   soundCopy:'Y says yuh at the start of yo-yo — a quick glide made with a wide smile. Y is a part-time letter: at the ends of words like happy it borrows the ee sound, but here it is the young consonant y.'},
  {intro:'A blue yo-yo swings in for the letter Y. Y glides — yuh — and spends its days going up and down, just like the toy on the card.',
   upperCopy:'Big Y is a small valley that turns into a tall line: slide down-right, meet in the middle, then straight down.',
   lowerCopy:'Little y is a short u with a tail that dives below the line and curls left — like little g’s tail pointing the other way.',
   pairCopy:'Big Y forks at the top; little y curls below the line. Say yuh, then move your hand like a yo-yo: up, down, up, down.',
   activity:{title:'Yo-yo hands',steps:['Make your hand a yo-yo: crouch down and rise up, saying yuh each time you stand.','Tie a soft toy to a string and swing it gently — up, down, yuh, yuh.','Count how many yo-yos you can do without laughing.']}},),
 L('z','Zebra','picture.png',1080,1350,
  'A zebra with golden-orange fur and dark stripes',
  {kind:'plain',soundSay:'z — zzz, a buzzing sound',beginningDistractors:['d','k'],
   soundCopy:'Z says zzz — a busy bee buzzing: voice on, tongue close behind the teeth. Hold it out: zzzz, then buzz it around the room like a bee finding flowers.'},
  {intro:'A striped zebra gallops in for the letter Z — the last letter of the alphabet, wearing the most striking coat of all. Z buzzes: zzz, like a bee at the finish line.',
   upperCopy:'Big Z is three straight lines: across the top, down the hill, across the bottom — drawn without lifting, like a zigzag slide.',
   lowerCopy:'Little z is the same zigzag between the lines: across, slide, across. One stroke, sharp corners.',
   pairCopy:'Big Z and little z both zigzag. Say zzz and trace the zigzag in the air, then on the floor with your toe.',
   activity:{title:'Zoo parade',steps:['March like a zoo parade, buzzing zzz with every step.','Striped-sock hunt: find the stripiest socks in the house and wear them on your hands like zebra puppets.','Gallop one final lap, buzz a long zzzz and bow — the alphabet is complete.']}},)
];

export const LETTERS_BY_KEY=Object.fromEntries(LETTERS.map(l=>[l.letter,l]));
export const letterAt=i=>LETTERS[(i%LETTERS.length+LETTERS.length)%LETTERS.length];
