import {beanActivity} from './bean-project.mjs';
export const sinkBase='https://pub-f2fcb7c9b45a496cbeefef18dbba0ec0.r2.dev/activities/science/sink-or-float/';
const image=p=>sinkBase+p.slug+'.webp';
export const sinkPages=[
 {slug:'sink-or-float-instructions',title:'Plan Your Sink or Float Experiment',intro:'Choose your materials, plan a fair test and draw your setup before you begin.',explain:'Use the guide with a grown-up. Test one object at a time and use the same gentle placing method each time. Keep the screen away from the tub; dry your hands before recording your work.',learn:'A clear plan helps you compare results. Changing several things at once makes it harder to explain what happened.',tasks:[{title:'My materials',prompt:'Draw the four safe objects your grown-up has chosen.',fields:['Our objects are…']},{title:'Our setup',prompt:'Draw where the tub and towel will go. Where will you keep your paper or device dry?',fields:['We will test on…','We will keep things dry by…']}],notes:[['One thing at a time','Remove each object before testing another. Place it gently and let go, so you observe what it does without a hand supporting it.'],['Watch, then record','Take time to look. An object may behave differently after it gets wet. Describe a change if you see one.']]},
 {slug:'sink-or-float-predictions',title:'My Sink or Float Predictions',intro:'Look closely at four objects. Make your predictions before testing them in water.',explain:'Name each object and think about its material and shape. Predict whether it will sink or float, and explain why. Keep your original predictions so you can compare them with your results.',learn:'A prediction is an idea we can test. A surprising result is useful evidence, not a wrong answer to hide.',tasks:[1,2,3,4].map(n=>({title:'Object '+n,prompt:'Draw your object and say what you think it will do.',fields:['Object name','I predict sink or float because…']})),notes:[['Look beyond size','A large object can float and a smaller one can sink. Consider what it is made of and whether it contains air.'],['Keep your first idea','Do not change a prediction after testing. Add what you learned to the results diary instead.']]},
 {slug:'sink-or-float-results',title:'My Sink or Float Results Diary',intro:'Record the evidence from four tests. Compare what you expected with what actually happened.',explain:'Use the same objects as your prediction sheet. Test each one with a grown-up. Record whether it floated, sank or changed after waiting. Draw its position in the water.',learn:'An observation describes what you actually see. Comparing predictions with observations helps you revise your ideas.',tasks:[1,2,3,4].map(n=>({title:'Test '+n,prompt:'Draw where the object ended up in the water.',fields:['Object name','My prediction was…','I observed…']})),notes:[['Use clear words','“The spoon settled on the bottom” tells us more than “it worked”. Describe where your object was and what it did.'],['Record changes too','If an object floated at first but sank later, record both. Wetting, water entering a hollow object or trapped air escaping can affect the result.']]},
 {slug:'sink-or-float-sorting',title:'Sort Your Sink or Float Discoveries',intro:'Use your real results to group objects that sank and objects that floated.',explain:'Look back at your results diary. Draw or name the objects in the matching group below. If something changed during the test, explain that separately instead of forcing it into one group.',learn:'Sorting helps us spot patterns. Our groups should follow the evidence from our own experiment.',tasks:[{title:'Objects that sank',prompt:'Draw the objects that settled on the bottom.',fields:['These objects sank…']},{title:'Objects that floated',prompt:'Draw the objects that stayed at the surface.',fields:['These objects floated…']},{title:'Something changed',prompt:'Did an object behave differently after waiting? Describe or draw what you saw.',fields:['At first…','Later…']}],notes:[['Compare your groups','What do the objects in each group have in common? Avoid assuming that everything made from one material must behave the same way.'],['Test a new idea','Choose one more safe object with a grown-up. Predict its group, test it and add it according to the result.']]},
 {slug:'foil-boat-challenge',title:'Build a Foil Boat',intro:'Shape, test and improve a boat made from one piece of foil. Can you keep its inside dry?',explain:'Fold the foil into a wide open boat with raised edges. Place it gently on the water. Observe whether it floats and whether water enters. Dry and reshape the same piece before a second test. Avoid tearing the foil.',learn:'A floating boat pushes water aside. Shape affects how much water it can displace before water comes over its edges. A redesign can improve the boat without adding more foil.',tasks:[{title:'My first boat',prompt:'Draw your first design. Show its base and raised edges.',fields:['My boat shape is…','When I tested it…']},{title:'My improved boat',prompt:'Change one feature, such as the base width or edge height. Draw the new design.',fields:['I changed…','The next test showed…']},{title:'What I learned',prompt:'Compare both designs. What would you try next?',fields:['The design that worked better was…','Next time I would…']}],notes:[['Keep it a fair comparison','Use the same foil and the same tub. Change one feature so you can explain which difference may have helped.'],['Watch the edges','If an edge dips below the surface, water can enter. A hole can also let water in. Describe what happened before redesigning.']]}
];
export const sinkLinks=(exclude)=>`<div class="bean-links">${sinkPages.filter(p=>p.slug!==exclude).map(p=>`<a href="/science/sink-or-float/${p.slug}/"><img class="bean-thumb" src="${image(p)}" width="1024" height="1536" alt="Preview of ${p.title}" loading="lazy"><strong>${p.title}</strong><p>${p.intro}</p><small>Draw · Type · Save</small></a>`).join('')}</div>`;
function explainer(p){return `<section class="bean-explainer"><div class="bean-explainer-intro"><a href="${image(p)}"><img src="${image(p)}" width="1024" height="1536" alt="${p.title} worksheet preview" loading="lazy"></a><div><h2>Explore before you start.</h2><p>Open the picture for a closer look, or use the drawing and writing areas below. You can also use paper beside your experiment.</p></div></div><div class="bean-lesson-grid">${p.notes.map(([t,d])=>`<section><h3>${t}</h3><p>${d}</p></section>`).join('')}</div></section>`;}
export const sinkActivity=p=>'<div class="sink-project">'+beanActivity(p,{image,links:sinkLinks,explainer,guide:'/science/sink-or-float/',safety:"An adult stays beside you throughout water play. Use a shallow plastic tub and objects too large to swallow. Avoid glass, sharp objects and items with batteries. Keep your screen dry and away from the water. Do not drink the water. Dry spills and empty the tub when finished."})+'</div>';
